# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_exchange"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:
    #   Message Destinations:
    #     exchange_get_mailbox_info
    #   Functions:
    #     exchange_get_mailbox_info


    yield ImportDefinition(u"""
eyJ0YXNrX29yZGVyIjogW10sICJ3b3JrZmxvd3MiOiBbXSwgImFjdGlvbnMiOiBbXSwgImxheW91
dHMiOiBbXSwgImV4cG9ydF9mb3JtYXRfdmVyc2lvbiI6IDIsICJpZCI6IDIsICJpbmR1c3RyaWVz
IjogbnVsbCwgInBoYXNlcyI6IFtdLCAiYWN0aW9uX29yZGVyIjogW10sICJnZW9zIjogbnVsbCwg
InNlcnZlcl92ZXJzaW9uIjogeyJtYWpvciI6IDMxLCAidmVyc2lvbiI6ICIzMS4wLjQwMjYiLCAi
YnVpbGRfbnVtYmVyIjogNDAyNiwgIm1pbm9yIjogMH0sICJ0aW1lZnJhbWVzIjogbnVsbCwgIndv
cmtzcGFjZXMiOiBbXSwgImF1dG9tYXRpY190YXNrcyI6IFtdLCAiZnVuY3Rpb25zIjogW3siZGlz
cGxheV9uYW1lIjogImV4Y2hhbmdlX2dldF9tYWlsYm94X2luZm8iLCAidXVpZCI6ICIzNGYxZTgz
OC0yODMzLTRkNDItOGYwYS01OWIyZDVkMDdmNGMiLCAiY3JlYXRvciI6IHsiZGlzcGxheV9uYW1l
IjogIlJlc2lsaWVudCBTeXNhZG1pbiIsICJ0eXBlIjogInVzZXIiLCAiaWQiOiAyLCAibmFtZSI6
ICJhQGEuY29tIn0sICJ2aWV3X2l0ZW1zIjogW10sICJleHBvcnRfa2V5IjogImV4Y2hhbmdlX2dl
dF9tYWlsYm94X2luZm8iLCAibGFzdF9tb2RpZmllZF9ieSI6IHsiZGlzcGxheV9uYW1lIjogIlJl
c2lsaWVudCBTeXNhZG1pbiIsICJ0eXBlIjogInVzZXIiLCAiaWQiOiAyLCAibmFtZSI6ICJhQGEu
Y29tIn0sICJuYW1lIjogImV4Y2hhbmdlX2dldF9tYWlsYm94X2luZm8iLCAidmVyc2lvbiI6IDAs
ICJ3b3JrZmxvd3MiOiBbXSwgImxhc3RfbW9kaWZpZWRfdGltZSI6IDE1MzI3MTI1ODM5MTQsICJk
ZXN0aW5hdGlvbl9oYW5kbGUiOiAiZXhjaGFuZ2VfZ2V0X21haWxib3hfaW5mbyIsICJpZCI6IDEs
ICJkZXNjcmlwdGlvbiI6IHsiY29udGVudCI6ICJHZXQgbWFpbGJveCBpbmZvIGZyb20gZXhjaGFu
Z2UiLCAiZm9ybWF0IjogInRleHQifX1dLCAibm90aWZpY2F0aW9ucyI6IG51bGwsICJyZWd1bGF0
b3JzIjogbnVsbCwgImluY2lkZW50X3R5cGVzIjogW3siY3JlYXRlX2RhdGUiOiAxNTMyNzE2MTc5
ODU3LCAiZGVzY3JpcHRpb24iOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwg
ImV4cG9ydF9rZXkiOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgImlkIjog
MCwgIm5hbWUiOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgInVwZGF0ZV9k
YXRlIjogMTUzMjcxNjE3OTg1NywgInV1aWQiOiAiYmZlZWMyZDQtMzc3MC0xMWU4LWFkMzktNGEw
MDA0MDQ0YWEwIiwgImVuYWJsZWQiOiBmYWxzZSwgInN5c3RlbSI6IGZhbHNlLCAicGFyZW50X2lk
IjogbnVsbCwgImhpZGRlbiI6IGZhbHNlfV0sICJzY3JpcHRzIjogW10sICJ0eXBlcyI6IFtdLCAi
bWVzc2FnZV9kZXN0aW5hdGlvbnMiOiBbeyJ1dWlkIjogImRmY2UzYjUzLTdmNDAtNGU3Yy1iMjQ5
LTdjNGQ1YmJmY2FkYiIsICJleHBvcnRfa2V5IjogImV4Y2hhbmdlX2dldF9tYWlsYm94X2luZm8i
LCAibmFtZSI6ICJleGNoYW5nZV9nZXRfbWFpbGJveF9pbmZvIiwgImRlc3RpbmF0aW9uX3R5cGUi
OiAwLCAicHJvZ3JhbW1hdGljX25hbWUiOiAiZXhjaGFuZ2VfZ2V0X21haWxib3hfaW5mbyIsICJl
eHBlY3RfYWNrIjogdHJ1ZSwgInVzZXJzIjogWyJhQGEuY29tIl19XSwgImluY2lkZW50X2FydGlm
YWN0X3R5cGVzIjogW10sICJyb2xlcyI6IFtdLCAiZmllbGRzIjogW3sib3BlcmF0aW9ucyI6IFtd
LCAicmVhZF9vbmx5IjogdHJ1ZSwgInV1aWQiOiAiYzNmMGUzZWQtMjFlMS00ZDUzLWFmZmItZmU1
Y2EzMzA4Y2NhIiwgInRlbXBsYXRlcyI6IFtdLCAidHlwZV9pZCI6IDAsICJjaG9zZW4iOiBmYWxz
ZSwgInRleHQiOiAiU2ltdWxhdGlvbiIsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxz
ZSwgImV4cG9ydF9rZXkiOiAiaW5jaWRlbnQvaW5jX3RyYWluaW5nIiwgInRvb2x0aXAiOiAiV2hl
dGhlciB0aGUgaW5jaWRlbnQgaXMgYSBzaW11bGF0aW9uIG9yIGEgcmVndWxhciBpbmNpZGVudC4g
IFRoaXMgZmllbGQgaXMgcmVhZC1vbmx5LiIsICJyaWNoX3RleHQiOiBmYWxzZSwgIm9wZXJhdGlv
bl9wZXJtcyI6IHt9LCAicHJlZml4IjogbnVsbCwgImludGVybmFsIjogZmFsc2UsICJ2YWx1ZXMi
OiBbXSwgImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiaW5wdXRfdHlwZSI6ICJib29sZWFuIiwgImNo
YW5nZWFibGUiOiB0cnVlLCAiaGlkZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlkIjogMzgsICJu
YW1lIjogImluY190cmFpbmluZyJ9XSwgIm92ZXJyaWRlcyI6IFtdLCAiZXhwb3J0X2RhdGUiOiAx
NTMyNzEyNjIwMzA2fQ==
"""
    )
