#!/bin/sh
#
# A git hook script to check the commit message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
# The hook checks for 2 conventions in a commit message:
# 1: A JIRA Ticket Number; SOARAPPS-XXXX
# Full example: SOARAPPS-123 added a new feature to fn_utilities
# 
# This also accepts a "Merge"
# Full example: "Merge branch 'master' into story/SOARAPPS-3104_improve_build"
# regex to validate in commit msg

commit_regex='(^Merge|INT-\d+|SOARAPPS-\d+)'
error_msg="INVALID COMMIT MESSAGE. Your commit message is either missing a JIRA Issue ('SOARAPPS-1111'), or if its a merge should start with ('Merge'). Example: SOARAPPS-123 added new cool action to my package"

# Ensure the commit message contains the ticket 
if ! grep -iqE "$commit_regex" "$1"; then
    # else print the error message 
    echo "$error_msg" >&2
    exit 1
fi
