{
    "action_order": [],
    "actions": [{
        "automations": [],
        "conditions": [{
            "evaluation_id": null,
            "field_name": "artifact.type",
            "method": "in",
            "type": null,
            "value": ["Email Sender", "Email Recipient"]
        }],
        "enabled": true,
        "export_key": "Have I Been Pwned Hits",
        "id": 24,
        "logic_type": "all",
        "message_destinations": [],
        "name": "Have I Been Pwned Hits",
        "object_type": "artifact",
        "tags": [{
            "tag_handle": "fn_hibp",
            "value": null
        }],
        "timeout_seconds": 86400,
        "type": 0,
        "uuid": "13f520e0-d1f8-41f7-9a2d-5ada982da33e",
        "view_items": [],
        "workflows": ["have_i_been_pwned_hits"]
    }],
    "apps": [],
    "automatic_tasks": [],
    "export_date": 1650291770577,
    "export_format_version": 2,
    "export_type": null,
    "fields": [{
        "export_key": "incident/internal_customizations_field",
        "id": 0,
        "input_type": "text",
        "internal": true,
        "name": "internal_customizations_field",
        "read_only": true,
        "text": "Customizations Field (internal)",
        "type_id": 0,
        "uuid": "bfeec2d4-3770-11e8-ad39-4a0004044aa1"
    }],
    "functions": [],
    "geos": null,
    "groups": null,
    "id": 86,
    "inbound_destinations": [],
    "inbound_mailboxes": null,
    "incident_artifact_types": [],
    "incident_types": [{
        "update_date": 1650291767748,
        "create_date": 1650291767748,
        "uuid": "bfeec2d4-3770-11e8-ad39-4a0004044aa0",
        "description": "Customization Packages (internal)",
        "export_key": "Customization Packages (internal)",
        "name": "Customization Packages (internal)",
        "enabled": false,
        "system": false,
        "parent_id": null,
        "hidden": false,
        "id": 0
    }],
    "industries": null,
    "layouts": [],
    "locale": null,
    "message_destinations": [],
    "notifications": null,
    "overrides": [],
    "phases": [],
    "playbooks": null,
    "regulators": null,
    "roles": [],
    "scripts": [],
    "server_version": {
        "build_number": 49,
        "major": 43,
        "minor": 1,
        "version": "43.1.49"
    },
    "tags": [],
    "task_order": [],
    "timeframes": null,
    "types": [],
    "workflows": [{
        "actions": [],
        "content": {
            "version": 14,
            "workflow_id": "have_i_been_pwned_hits",
            "xml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><definitions xmlns=\"http://www.omg.org/spec/BPMN/20100524/MODEL\" xmlns:bpmndi=\"http://www.omg.org/spec/BPMN/20100524/DI\" xmlns:omgdc=\"http://www.omg.org/spec/DD/20100524/DC\" xmlns:omgdi=\"http://www.omg.org/spec/DD/20100524/DI\" xmlns:resilient=\"http://resilient.ibm.com/bpmn\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" targetNamespace=\"http://www.camunda.org/test\"><process id=\"have_i_been_pwned_hits\" isExecutable=\"true\" name=\"Have I Been Pwned Hits\"><documentation>Queries Have I Been Pwned for breaches and pastes given an email address as an input. This Workflow requires SOAR v43 or greater in order to add hits to the artifact.</documentation><startEvent id=\"StartEvent_155asxm\"><outgoing>SequenceFlow_02wr3yn</outgoing></startEvent><endEvent id=\"EndEvent_1mfswgb\"><incoming>SequenceFlow_1gf97rs</incoming></endEvent><sequenceFlow id=\"SequenceFlow_02wr3yn\" sourceRef=\"StartEvent_155asxm\" targetRef=\"ServiceTask_1lil4kk\"/><serviceTask id=\"ServiceTask_1lil4kk\" name=\"Have I Been Pwned Get Breaches\" resilient:type=\"function\"><extensionElements><resilient:function uuid=\"fe751617-4ee9-43e8-b35d-a6bf419b65d5\">{\"inputs\":{},\"post_processing_script\":\"if results.success:\\n  if results.content:\\n    hit = []\\n    resp_data = results.content\\n    hit = [\\n      {\\n        \\\"name\\\": \\\"Breached Sites\\\", \\n        \\\"type\\\": \\\"number\\\",\\n        \\\"value\\\": \\\"{}\\\".format(resp_data)\\n      }\\n    ]\\n    artifact.addHit(\\\"HIBP Function hits added\\\", hit)\\nelse:\\n  incident.addNote(\\\"Have I Been Pwned has failed: {}\\\".format(results.reason))\\n\",\"post_processing_script_language\":\"python3\",\"pre_processing_script\":\"inputs.email_address = artifact.value\",\"pre_processing_script_language\":\"python3\"}</resilient:function></extensionElements><incoming>SequenceFlow_02wr3yn</incoming><outgoing>SequenceFlow_0qi6gq3</outgoing></serviceTask><sequenceFlow id=\"SequenceFlow_0qi6gq3\" sourceRef=\"ServiceTask_1lil4kk\" targetRef=\"ServiceTask_1xvcgql\"/><serviceTask id=\"ServiceTask_1xvcgql\" name=\"Have I Been Pwned Get Pastes\" resilient:type=\"function\"><extensionElements><resilient:function uuid=\"d448bee5-d85e-484e-a91c-274ebae67123\">{\"inputs\":{},\"post_processing_script\":\"if results.success:\\n  if results.content:\\n    hit = []\\n    resp_data = results.content\\n    hit = [\\n      {\\n        \\\"name\\\": \\\"Pastes\\\", \\n        \\\"type\\\": \\\"number\\\",\\n        \\\"value\\\": \\\"{}\\\".format(resp_data)\\n      }\\n    ]\\n    artifact.addHit(\\\"HIBP Function hits added\\\", hit)\\nelse:\\n  incident.addNote(\\\"Have I Been Pwned has failed: {}\\\".format(results.reason))\\n\\n    \",\"post_processing_script_language\":\"python3\",\"pre_processing_script\":\"inputs.email_address = artifact.value\",\"pre_processing_script_language\":\"python3\"}</resilient:function></extensionElements><incoming>SequenceFlow_0qi6gq3</incoming><outgoing>SequenceFlow_1gf97rs</outgoing></serviceTask><sequenceFlow id=\"SequenceFlow_1gf97rs\" sourceRef=\"ServiceTask_1xvcgql\" targetRef=\"EndEvent_1mfswgb\"/><textAnnotation id=\"TextAnnotation_1kxxiyt\"><text>Start your workflow here</text></textAnnotation><association id=\"Association_1seuj48\" sourceRef=\"StartEvent_155asxm\" targetRef=\"TextAnnotation_1kxxiyt\"/><textAnnotation id=\"TextAnnotation_0hlds8j\"><text>Results are returned as a hit in the artifact</text></textAnnotation><association id=\"Association_1ef0l75\" sourceRef=\"ServiceTask_1lil4kk\" targetRef=\"TextAnnotation_0hlds8j\"/><textAnnotation id=\"TextAnnotation_1xu4goa\"><text>Results are returned as a hit in the artifact</text></textAnnotation><association id=\"Association_0c6m2tx\" sourceRef=\"ServiceTask_1xvcgql\" targetRef=\"TextAnnotation_1xu4goa\"/></process><bpmndi:BPMNDiagram id=\"BPMNDiagram_1\"><bpmndi:BPMNPlane bpmnElement=\"undefined\" id=\"BPMNPlane_1\"><bpmndi:BPMNShape bpmnElement=\"StartEvent_155asxm\" id=\"StartEvent_155asxm_di\"><omgdc:Bounds height=\"36\" width=\"36\" x=\"162\" y=\"188\"/><bpmndi:BPMNLabel><omgdc:Bounds height=\"0\" width=\"90\" x=\"157\" y=\"223\"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNShape bpmnElement=\"TextAnnotation_1kxxiyt\" id=\"TextAnnotation_1kxxiyt_di\"><omgdc:Bounds height=\"30\" width=\"100\" x=\"99\" y=\"254\"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement=\"Association_1seuj48\" id=\"Association_1seuj48_di\"><omgdi:waypoint x=\"169\" xsi:type=\"omgdc:Point\" y=\"220\"/><omgdi:waypoint x=\"153\" xsi:type=\"omgdc:Point\" y=\"254\"/></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement=\"EndEvent_1mfswgb\" id=\"EndEvent_1mfswgb_di\"><omgdc:Bounds height=\"36\" width=\"36\" x=\"639\" y=\"188\"/><bpmndi:BPMNLabel><omgdc:Bounds height=\"13\" width=\"0\" x=\"657\" y=\"227\"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement=\"SequenceFlow_02wr3yn\" id=\"SequenceFlow_02wr3yn_di\"><omgdi:waypoint x=\"198\" xsi:type=\"omgdc:Point\" y=\"206\"/><omgdi:waypoint x=\"280\" xsi:type=\"omgdc:Point\" y=\"206\"/><bpmndi:BPMNLabel><omgdc:Bounds height=\"13\" width=\"0\" x=\"239\" y=\"184.5\"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement=\"ServiceTask_1lil4kk\" id=\"ServiceTask_1lil4kk_di\"><omgdc:Bounds height=\"80\" width=\"100\" x=\"280\" y=\"166\"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement=\"SequenceFlow_0qi6gq3\" id=\"SequenceFlow_0qi6gq3_di\"><omgdi:waypoint x=\"380\" xsi:type=\"omgdc:Point\" y=\"206\"/><omgdi:waypoint x=\"458\" xsi:type=\"omgdc:Point\" y=\"206\"/><bpmndi:BPMNLabel><omgdc:Bounds height=\"13\" width=\"0\" x=\"419\" y=\"184.5\"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement=\"ServiceTask_1xvcgql\" id=\"ServiceTask_1xvcgql_di\"><omgdc:Bounds height=\"80\" width=\"100\" x=\"457.93536804308803\" y=\"166\"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement=\"SequenceFlow_1gf97rs\" id=\"SequenceFlow_1gf97rs_di\"><omgdi:waypoint x=\"558\" xsi:type=\"omgdc:Point\" y=\"206\"/><omgdi:waypoint x=\"639\" xsi:type=\"omgdc:Point\" y=\"206\"/><bpmndi:BPMNLabel><omgdc:Bounds height=\"13\" width=\"0\" x=\"598.5\" y=\"184\"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement=\"TextAnnotation_0hlds8j\" id=\"TextAnnotation_0hlds8j_di\"><omgdc:Bounds height=\"52\" width=\"107\" x=\"368\" y=\"60\"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement=\"Association_1ef0l75\" id=\"Association_1ef0l75_di\"><omgdi:waypoint x=\"361\" xsi:type=\"omgdc:Point\" y=\"166\"/><omgdi:waypoint x=\"402\" xsi:type=\"omgdc:Point\" y=\"112\"/></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement=\"TextAnnotation_1xu4goa\" id=\"TextAnnotation_1xu4goa_di\"><omgdc:Bounds height=\"54\" width=\"116\" x=\"577\" y=\"60\"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement=\"Association_0c6m2tx\" id=\"Association_0c6m2tx_di\"><omgdi:waypoint x=\"549\" xsi:type=\"omgdc:Point\" y=\"167\"/><omgdi:waypoint x=\"606\" xsi:type=\"omgdc:Point\" y=\"114\"/></bpmndi:BPMNEdge></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></definitions>"
        },
        "content_version": 14,
        "creator_id": "admin@example.com",
        "description": "Queries Have I Been Pwned for breaches and pastes given an email address as an input. This Workflow requires SOAR v43 or greater in order to add hits to the artifact.",
        "export_key": "have_i_been_pwned_hits",
        "last_modified_by": "admin@example.com",
        "last_modified_time": 1650052423019,
        "name": "Have I Been Pwned Hits",
        "object_type": "artifact",
        "programmatic_name": "have_i_been_pwned_hits",
        "tags": [{
            "tag_handle": "fn_hibp",
            "value": null
        }],
        "uuid": "433dfb15-b9cc-46ce-a681-ecdba7267f27",
        "workflow_id": 19
    }],
    "workspaces": []
}