# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_splunk_integration"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # Function-field definitions
    yield TypeDefinition(
        {
            "type_name": "__function",
            "fields": { '00c3475d-4026-4301-b73c-dc29fc7869b8': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_threat_intel_type',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_threat_intel_type',
                                            'tooltip': '',
                                            'uuid': '00c3475d-4026-4301-b73c-dc29fc7869b8',
                                            'values': []},
  '13d39604-e948-43b9-95b2-5d39529e7145': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param5',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param5',
                                            'tooltip': '',
                                            'uuid': '13d39604-e948-43b9-95b2-5d39529e7145',
                                            'values': []},
  '174ae898-a813-4379-b322-ba20e850a400': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_threat_intel_key',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_threat_intel_key',
                                            'tooltip': 'The _key from Splunk ES for this threat_intel item',
                                            'uuid': '174ae898-a813-4379-b322-ba20e850a400',
                                            'values': []},
  '4af32ba8-92cb-4bd7-a5b2-9e48c2618863': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param3',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param3',
                                            'tooltip': '',
                                            'uuid': '4af32ba8-92cb-4bd7-a5b2-9e48c2618863',
                                            'values': []},
  '5c8543bc-a513-4a47-90c6-1af4215b5e1f': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param4',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param4',
                                            'tooltip': '',
                                            'uuid': '5c8543bc-a513-4a47-90c6-1af4215b5e1f',
                                            'values': []},
  '5dcd2998-9222-44cf-b047-418d672fbf0c': { 'blank_option': False,
                                            'input_type': 'number',
                                            'name': 'notable_event_status',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'notable_event_status',
                                            'tooltip': '',
                                            'uuid': '5dcd2998-9222-44cf-b047-418d672fbf0c',
                                            'values': []},
  '6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758': { 'blank_option': False,
                                            'input_type': 'boolean',
                                            'name': 'splunk_verify_cert',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_verify_cert',
                                            'tooltip': '',
                                            'uuid': '6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758',
                                            'values': []},
  '7341377c-62c3-4565-aa76-b33bc8a5bcb4': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param9',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param9',
                                            'tooltip': '',
                                            'uuid': '7341377c-62c3-4565-aa76-b33bc8a5bcb4',
                                            'values': []},
  '747afc0e-82a0-4def-acab-edd06f61f81e': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'comment',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'comment',
                                            'tooltip': 'Update the notable comment using this',
                                            'uuid': '747afc0e-82a0-4def-acab-edd06f61f81e',
                                            'values': []},
  '85ecf916-d844-4b3c-a89f-5273bf3835a3': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param2',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param2',
                                            'tooltip': '',
                                            'uuid': '85ecf916-d844-4b3c-a89f-5273bf3835a3',
                                            'values': []},
  'b2ed2dd3-0b7d-4dc9-b4ae-dad49d34b124': { 'blank_option': False,
                                            'input_type': 'textarea',
                                            'name': 'splunk_query',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [ { 'name': 'search index for type',
                                                             'template': 'search index = %param1% AND %param2% = %param3%'},
                                                           { 'name': 'search thread_intel for type',
                                                             'template': 'inputlookup %param1% | search %param2%=%param3% | eval item_key=_key'},
                                                           { 'name': 'search index and source for type',
                                                             'template': 'search index = %param1% source=%param2% AND %param3%=%param4%'}],
                                            'text': 'splunk_query',
                                            'tooltip': '',
                                            'uuid': 'b2ed2dd3-0b7d-4dc9-b4ae-dad49d34b124',
                                            'values': []},
  'c51b4789-9132-4f0f-b5a6-b882b98277de': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param10',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param10',
                                            'tooltip': '',
                                            'uuid': 'c51b4789-9132-4f0f-b5a6-b882b98277de',
                                            'values': []},
  'd3c6002c-826a-41ce-9cca-67e94cda8fc0': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'event_id',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'event_id',
                                            'tooltip': 'notable event id from splunk ES',
                                            'uuid': 'd3c6002c-826a-41ce-9cca-67e94cda8fc0',
                                            'values': []},
  'de435906-91b7-4b74-80ec-3de099cacdd6': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param7',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param7',
                                            'tooltip': '',
                                            'uuid': 'de435906-91b7-4b74-80ec-3de099cacdd6',
                                            'values': []},
  'e584a13e-0bb5-4996-8a53-1f74f9a8ca0e': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param6',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param6',
                                            'tooltip': '',
                                            'uuid': 'e584a13e-0bb5-4996-8a53-1f74f9a8ca0e',
                                            'values': []},
  'ebf0aa1d-8286-4465-91fb-2a4a4943f22d': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param8',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param8',
                                            'tooltip': '',
                                            'uuid': 'ebf0aa1d-8286-4465-91fb-2a4a4943f22d',
                                            'values': []},
  'ed2ef56f-a3f2-46c8-bff3-6c28a5e708e8': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'splunk_query_param1',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_query_param1',
                                            'tooltip': '',
                                            'uuid': 'ed2ef56f-a3f2-46c8-bff3-6c28a5e708e8',
                                            'values': []},
  'f4243c42-ed46-4b74-b28e-7b99c021ec7b': { 'blank_option': False,
                                            'input_type': 'number',
                                            'name': 'splunk_max_return',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'splunk_max_return',
                                            'tooltip': 'max number of events to return (used in head max)',
                                            'uuid': 'f4243c42-ed46-4b74-b28e-7b99c021ec7b',
                                            'values': []}}
        }
    )

    # Message destination: 'splunk_es_notable'
    yield MessageDestinationDefinition({ 'destination_type': 0,
  'expect_ack': True,
  'name': 'splunk_es_notable',
  'programmatic_name': 'splunk_es_notable'}
    )

    # Message destination: 'splunk_es_rest'
    yield MessageDestinationDefinition({ 'destination_type': 0,
  'expect_ack': True,
  'name': 'splunk_es_rest',
  'programmatic_name': 'splunk_es_rest'}
    )

    # Message destination: 'splunk_search'
    yield MessageDestinationDefinition({ 'destination_type': 0,
  'expect_ack': True,
  'name': 'splunk_search',
  'programmatic_name': 'splunk_search'}
    )

    # Function: 'splunk_update_notable'
    yield FunctionDefinition({ 'description': { 'content': 'Update notable events according to the status of the corresponding incident.\n\nInputs: \nevent_id: the notable event id in the splunk_notable_event_id field\ncomment: add a note to the notable event \nstatus: Notable event status. Integer: 2=active, 5= closed\nverify: Verify the certificate or not. Set it to false if the cert of your splunk server is a self-signed cert.',
                   'format': 'text'},
  'destination_handle': 'splunk_es_notable',
  'display_name': 'Splunk Update Notable Event',
  'name': 'splunk_update_notable',
  'uuid': '7797e5b5-bf54-4d48-aa2f-215f66ccc2ef',
  'view_items': [ { 'content': 'd3c6002c-826a-41ce-9cca-67e94cda8fc0',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '747afc0e-82a0-4def-acab-edd06f61f81e',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '5dcd2998-9222-44cf-b047-418d672fbf0c',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758',
                    'element': 'field_uuid',
                    'field_type': '__function'}]}
    )

    # Function: 'splunk_delete_threat_intel_item'
    yield FunctionDefinition({ 'description': { 'content': 'Delete a threat intel item:\nsplunk_threat_intel_type: ip_intel, email_intel....., registry_intel\nsplunk_threat_intel_key: _key returned from Splunk ES for this item\nsplunk_verify_cert: False to skipping the validation of https cert.',
                   'format': 'text'},
  'destination_handle': 'splunk_es_rest',
  'display_name': 'Splunk Delete Intel Item',
  'name': 'splunk_delete_threat_intel_item',
  'uuid': '9260ef59-a3e1-4e76-ba26-f7c1688b1d59',
  'view_items': [ { 'content': '00c3475d-4026-4301-b73c-dc29fc7869b8',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '174ae898-a813-4379-b322-ba20e850a400',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758',
                    'element': 'field_uuid',
                    'field_type': '__function'}]}
    )

    # Function: 'splunk_search'
    yield FunctionDefinition({ 'description': { 'content': 'Pick a query string from the "Text with value string" template, and perform Splunk/SplunkES search',
                   'format': 'text'},
  'destination_handle': 'splunk_search',
  'display_name': 'Splunk Search',
  'name': 'splunk_search',
  'uuid': '86482013-45d6-47d3-b010-e95359f05299',
  'view_items': [ { 'content': 'b2ed2dd3-0b7d-4dc9-b4ae-dad49d34b124',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'ed2ef56f-a3f2-46c8-bff3-6c28a5e708e8',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '85ecf916-d844-4b3c-a89f-5273bf3835a3',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '4af32ba8-92cb-4bd7-a5b2-9e48c2618863',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '5c8543bc-a513-4a47-90c6-1af4215b5e1f',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '13d39604-e948-43b9-95b2-5d39529e7145',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'f4243c42-ed46-4b74-b28e-7b99c021ec7b',
                    'element': 'field_uuid',
                    'field_type': '__function'}]}
    )

    # Function: 'splunk_add_intel_item'
    yield FunctionDefinition({ 'description': { 'content': 'Add a new splunk es threat intelligence item to the collections\nsplunk_thread_intel_type: ip_intel, user_intel,...., or registry_intel\nsplunk_query_param1: field1 name of the dict used to create the item;\nsplunk_query_param2: field1 value;\nsplunk_query_param3: field2 name;\nsplunk_query_param4: field2 value;\n.....',
                   'format': 'text'},
  'destination_handle': 'splunk_es_rest',
  'display_name': 'Splunk Add Intel Item',
  'name': 'splunk_add_intel_item',
  'uuid': '2d9b53f7-d84e-4159-ba9e-d6c2b9c7e28e',
  'view_items': [ { 'content': '00c3475d-4026-4301-b73c-dc29fc7869b8',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'ed2ef56f-a3f2-46c8-bff3-6c28a5e708e8',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '85ecf916-d844-4b3c-a89f-5273bf3835a3',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '4af32ba8-92cb-4bd7-a5b2-9e48c2618863',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '5c8543bc-a513-4a47-90c6-1af4215b5e1f',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '13d39604-e948-43b9-95b2-5d39529e7145',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'e584a13e-0bb5-4996-8a53-1f74f9a8ca0e',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'de435906-91b7-4b74-80ec-3de099cacdd6',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'ebf0aa1d-8286-4465-91fb-2a4a4943f22d',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '7341377c-62c3-4565-aa76-b33bc8a5bcb4',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'c51b4789-9132-4f0f-b5a6-b882b98277de',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758',
                    'element': 'field_uuid',
                    'field_type': '__function'}]}
    )

    # Workflow: 'splunk_update_notable'
    yield WorkflowDefinition({ 'content': { 'xml': '<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:resilient="http://resilient.ibm.com/bpmn" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.camunda.org/test"><process id="splunk_update_notable" isExecutable="true" name="Example of Updating Splunk ES According to Incident Status"><documentation>Automatically update notable event status according to the status of the incident</documentation><startEvent id="StartEvent_155asxm"><outgoing>SequenceFlow_1q6i0ny</outgoing></startEvent><serviceTask id="ServiceTask_0hmk2kr" name="Splunk Update Notable Event" resilient:type="function"><extensionElements><resilient:function uuid="7797e5b5-bf54-4d48-aa2f-215f66ccc2ef"><![CDATA[{"inputs":{"d3c6002c-826a-41ce-9cca-67e94cda8fc0":{"input_type":"static","static_input":{"text_value":null}},"747afc0e-82a0-4def-acab-edd06f61f81e":{"input_type":"static","static_input":{"text_value":null}},"5dcd2998-9222-44cf-b047-418d672fbf0c":{"input_type":"static","static_input":{"number_value":null}},"6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758":{"input_type":"static","static_input":{"boolean_value":false}}},"pre_processing_script":"inputs.event_id = incident.properties.splunk_notable_event_id\\n\\nif incident.plan_status == \\"C\\":\\n  inputs.notable_event_status = 5\\n  inputs.comment = \\"Resilient incident is closed\\"\\nelse:\\n  inputs.comment = \\"Reslient incident is active\\"\\n  inputs.notable_event_status = 2\\n  ","post_processing_script":null,"result_name":null}]]></resilient:function></extensionElements><incoming>SequenceFlow_1q6i0ny</incoming><outgoing>SequenceFlow_0wxcf4w</outgoing></serviceTask><sequenceFlow id="SequenceFlow_1q6i0ny" sourceRef="StartEvent_155asxm" targetRef="ServiceTask_0hmk2kr"/><endEvent id="EndEvent_1ahimz8"><incoming>SequenceFlow_0wxcf4w</incoming></endEvent><sequenceFlow id="SequenceFlow_0wxcf4w" sourceRef="ServiceTask_0hmk2kr" targetRef="EndEvent_1ahimz8"/><textAnnotation id="TextAnnotation_1kxxiyt"><text>Start your workflow here</text></textAnnotation><association id="Association_1seuj48" sourceRef="StartEvent_155asxm" targetRef="TextAnnotation_1kxxiyt"/></process><bpmndi:BPMNDiagram id="BPMNDiagram_1"><bpmndi:BPMNPlane bpmnElement="undefined" id="BPMNPlane_1"><bpmndi:BPMNShape bpmnElement="StartEvent_155asxm" id="StartEvent_155asxm_di"><omgdc:Bounds height="36" width="36" x="162" y="188"/><bpmndi:BPMNLabel><omgdc:Bounds height="0" width="90" x="157" y="223"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNShape bpmnElement="TextAnnotation_1kxxiyt" id="TextAnnotation_1kxxiyt_di"><omgdc:Bounds height="30" width="100" x="99" y="254"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="Association_1seuj48" id="Association_1seuj48_di"><omgdi:waypoint x="169" xsi:type="omgdc:Point" y="220"/><omgdi:waypoint x="153" xsi:type="omgdc:Point" y="254"/></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="ServiceTask_0hmk2kr" id="ServiceTask_0hmk2kr_di"><omgdc:Bounds height="80" width="100" x="365" y="169"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_1q6i0ny" id="SequenceFlow_1q6i0ny_di"><omgdi:waypoint x="198" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="282" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="282" xsi:type="omgdc:Point" y="209"/><omgdi:waypoint x="365" xsi:type="omgdc:Point" y="209"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="297" y="201"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="EndEvent_1ahimz8" id="EndEvent_1ahimz8_di"><omgdc:Bounds height="36" width="36" x="677.6958637469586" y="188"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="695.6958637469586" y="227"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_0wxcf4w" id="SequenceFlow_0wxcf4w_di"><omgdi:waypoint x="465" xsi:type="omgdc:Point" y="209"/><omgdi:waypoint x="571" xsi:type="omgdc:Point" y="209"/><omgdi:waypoint x="571" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="678" xsi:type="omgdc:Point" y="206"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="586" y="201"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></definitions>'},
  'object_type': 'incident',
  'programmatic_name': 'splunk_update_notable'}
    )

    # Workflow: 'splunk_add_new_ip_intel'
    yield WorkflowDefinition({ 'content': { 'xml': '<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:resilient="http://resilient.ibm.com/bpmn" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.camunda.org/test"><process id="splunk_add_new_ip_intel" isExecutable="true" name="Example of Adding Splunk ES ip_intel"><documentation><![CDATA[Add a new ip_intel using artifact value:\nparam splunk_threat_intel_type: ip_intel, user_intel,..., or registry_intel\nparam splunk_query_param1: field to add. ip, or domain for example\nparam splunk_query_param2: value of field\nparam splunk_query_param3: field\nparam splunk_query_param4: value\n.....]]></documentation><startEvent id="StartEvent_155asxm"><outgoing>SequenceFlow_0gpe3sj</outgoing></startEvent><serviceTask id="ServiceTask_1g2gak6" name="Splunk Add Intel Item" resilient:type="function"><extensionElements><resilient:function uuid="2d9b53f7-d84e-4159-ba9e-d6c2b9c7e28e"><![CDATA[{"inputs":{"00c3475d-4026-4301-b73c-dc29fc7869b8":{"input_type":"static","static_input":{"text_value":"ip_intel"}},"ed2ef56f-a3f2-46c8-bff3-6c28a5e708e8":{"input_type":"static","static_input":{"text_value":"ip"}}},"pre_processing_script":"inputs.splunk_query_param2 = artifact.value","post_processing_script":null,"result_name":null}]]></resilient:function></extensionElements><incoming>SequenceFlow_0gpe3sj</incoming><outgoing>SequenceFlow_01h31mw</outgoing></serviceTask><sequenceFlow id="SequenceFlow_0gpe3sj" sourceRef="StartEvent_155asxm" targetRef="ServiceTask_1g2gak6"/><endEvent id="EndEvent_0v67ij6"><incoming>SequenceFlow_01h31mw</incoming></endEvent><sequenceFlow id="SequenceFlow_01h31mw" sourceRef="ServiceTask_1g2gak6" targetRef="EndEvent_0v67ij6"/><textAnnotation id="TextAnnotation_1kxxiyt"><text>Start your workflow here</text></textAnnotation><association id="Association_1seuj48" sourceRef="StartEvent_155asxm" targetRef="TextAnnotation_1kxxiyt"/></process><bpmndi:BPMNDiagram id="BPMNDiagram_1"><bpmndi:BPMNPlane bpmnElement="undefined" id="BPMNPlane_1"><bpmndi:BPMNShape bpmnElement="StartEvent_155asxm" id="StartEvent_155asxm_di"><omgdc:Bounds height="36" width="36" x="162" y="188"/><bpmndi:BPMNLabel><omgdc:Bounds height="0" width="90" x="157" y="223"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNShape bpmnElement="TextAnnotation_1kxxiyt" id="TextAnnotation_1kxxiyt_di"><omgdc:Bounds height="30" width="100" x="99" y="254"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="Association_1seuj48" id="Association_1seuj48_di"><omgdi:waypoint x="169" xsi:type="omgdc:Point" y="220"/><omgdi:waypoint x="153" xsi:type="omgdc:Point" y="254"/></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="ServiceTask_1g2gak6" id="ServiceTask_1g2gak6_di"><omgdc:Bounds height="80" width="100" x="251" y="174"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_0gpe3sj" id="SequenceFlow_0gpe3sj_di"><omgdi:waypoint x="198" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="225" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="225" xsi:type="omgdc:Point" y="214"/><omgdi:waypoint x="251" xsi:type="omgdc:Point" y="214"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="240" y="203"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="EndEvent_0v67ij6" id="EndEvent_0v67ij6_di"><omgdc:Bounds height="36" width="36" x="451" y="188"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="469" y="227"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_01h31mw" id="SequenceFlow_01h31mw_di"><omgdi:waypoint x="351" xsi:type="omgdc:Point" y="214"/><omgdi:waypoint x="401" xsi:type="omgdc:Point" y="214"/><omgdi:waypoint x="401" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="451" xsi:type="omgdc:Point" y="206"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="416" y="203"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></definitions>'},
  'object_type': 'artifact',
  'programmatic_name': 'splunk_add_new_ip_intel'}
    )

    # Workflow: 'search_splunk_ip_intel'
    yield WorkflowDefinition({ 'content': { 'xml': '<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:resilient="http://resilient.ibm.com/bpmn" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.camunda.org/test"><process id="search_splunk_ip_intel" isExecutable="true" name="Example of Searching Splunk IP Intel"><documentation><![CDATA[Use the Splunk Search function to look for an ip_intel\nParameters:\nparam1 intel type from (ip_intel, file_intel, user_intel, http_intel, email_intel, service_intel, process_intel, registry_intel, certificate_intel)\nparam2: what field to search. For example for ip_intel we can search ip. \nparam3: value. For example the ip value if param2 is ip\n\nReturn:\nAn array of dicts. Each dictionary contains the fields of that intel item, depending on the type. Once important field is item_key, which uniquely identifies the item.]]></documentation><startEvent id="StartEvent_155asxm"><outgoing>SequenceFlow_06k08vo</outgoing></startEvent><serviceTask id="ServiceTask_047839z" name="Splunk Search" resilient:type="function"><extensionElements><resilient:function uuid="86482013-45d6-47d3-b010-e95359f05299"><![CDATA[{"inputs":{"b2ed2dd3-0b7d-4dc9-b4ae-dad49d34b124":{"input_type":"static","static_input":{"text_content_value":{"format":"text","content":"inputlookup %param1% | search NOT disabled=* AND %param2%=%param3% | eval item_key=_key"}}},"ed2ef56f-a3f2-46c8-bff3-6c28a5e708e8":{"input_type":"static","static_input":{"text_value":"ip_intel"}},"85ecf916-d844-4b3c-a89f-5273bf3835a3":{"input_type":"static","static_input":{"text_value":"ip"}}},"pre_processing_script":"inputs.splunk_query_param3 = artifact.value","post_processing_script":"for event in results.events:\\n  splunk_es_ip_intel = incident.addRow(\\"splunk_ip_intel\\")\\n  splunk_es_ip_intel.time=event.time\\n  splunk_es_ip_intel.ip_intel_description=event.description\\n  splunk_es_ip_intel.ip_intel_ip=event.ip\\n  splunk_es_ip_intel.intel_item_key=event._key \\n  splunk_es_ip_intel.threat_key=event.threat_key","result_name":null}]]></resilient:function></extensionElements><incoming>SequenceFlow_06k08vo</incoming><outgoing>SequenceFlow_17k5670</outgoing></serviceTask><sequenceFlow id="SequenceFlow_06k08vo" sourceRef="StartEvent_155asxm" targetRef="ServiceTask_047839z"/><endEvent id="EndEvent_0uufwag"><incoming>SequenceFlow_17k5670</incoming></endEvent><sequenceFlow id="SequenceFlow_17k5670" sourceRef="ServiceTask_047839z" targetRef="EndEvent_0uufwag"/><textAnnotation id="TextAnnotation_1kxxiyt"><text>Start your workflow here</text></textAnnotation><association id="Association_1seuj48" sourceRef="StartEvent_155asxm" targetRef="TextAnnotation_1kxxiyt"/></process><bpmndi:BPMNDiagram id="BPMNDiagram_1"><bpmndi:BPMNPlane bpmnElement="undefined" id="BPMNPlane_1"><bpmndi:BPMNShape bpmnElement="StartEvent_155asxm" id="StartEvent_155asxm_di"><omgdc:Bounds height="36" width="36" x="162" y="188"/><bpmndi:BPMNLabel><omgdc:Bounds height="0" width="90" x="157" y="223"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNShape bpmnElement="TextAnnotation_1kxxiyt" id="TextAnnotation_1kxxiyt_di"><omgdc:Bounds height="30" width="100" x="99" y="254"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="Association_1seuj48" id="Association_1seuj48_di"><omgdi:waypoint x="169" xsi:type="omgdc:Point" y="220"/><omgdi:waypoint x="153" xsi:type="omgdc:Point" y="254"/></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="ServiceTask_047839z" id="ServiceTask_047839z_di"><omgdc:Bounds height="80" width="100" x="297.09653465346537" y="165.95420792079207"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_06k08vo" id="SequenceFlow_06k08vo_di"><omgdi:waypoint x="198" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="297" xsi:type="omgdc:Point" y="206"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="247.5" y="184.5"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="EndEvent_0uufwag" id="EndEvent_0uufwag_di"><omgdc:Bounds height="36" width="36" x="531.8470744680851" y="188"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="549.8470744680851" y="227"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_17k5670" id="SequenceFlow_17k5670_di"><omgdi:waypoint x="397" xsi:type="omgdc:Point" y="206"/><omgdi:waypoint x="532" xsi:type="omgdc:Point" y="206"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="464.5" y="184.5"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></definitions>'},
  'object_type': 'artifact',
  'programmatic_name': 'search_splunk_ip_intel'}
    )

    # Workflow: 'delete_splunk_es_threat_intel_item'
    yield WorkflowDefinition({ 'content': { 'xml': '<?xml version="1.0" encoding="UTF-8"?><definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL" xmlns:bpmndi="http://www.omg.org/spec/BPMN/20100524/DI" xmlns:omgdc="http://www.omg.org/spec/DD/20100524/DC" xmlns:omgdi="http://www.omg.org/spec/DD/20100524/DI" xmlns:resilient="http://resilient.ibm.com/bpmn" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://www.camunda.org/test"><process id="delete_splunk_es_threat_intel_item" isExecutable="true" name="Example of Deleting Splunk ES threat intel item"><documentation><![CDATA[This is an example of calling the "splunk delete threat intel item" to delete a ip_intel item:\nparam]]></documentation><startEvent id="StartEvent_155asxm"><outgoing>SequenceFlow_1te3lq4</outgoing></startEvent><serviceTask id="ServiceTask_1bez5fk" name="splunk delete threat intel item" resilient:type="function"><extensionElements><resilient:function uuid="9260ef59-a3e1-4e76-ba26-f7c1688b1d59"><![CDATA[{"inputs":{"00c3475d-4026-4301-b73c-dc29fc7869b8":{"input_type":"static","static_input":{"text_value":"ip_intel"}},"6f6a7f2c-a26b-4377-9f55-dd7f3c6b2758":{"input_type":"static","static_input":{"boolean_value":false}}},"pre_processing_script":"inputs.splunk_threat_intel_key = row.intel_item_key","post_processing_script":null,"result_name":null}]]></resilient:function></extensionElements><incoming>SequenceFlow_1te3lq4</incoming><outgoing>SequenceFlow_1y0amk9</outgoing></serviceTask><sequenceFlow id="SequenceFlow_1te3lq4" sourceRef="StartEvent_155asxm" targetRef="ServiceTask_1bez5fk"/><endEvent id="EndEvent_090sn33"><incoming>SequenceFlow_1y0amk9</incoming></endEvent><sequenceFlow id="SequenceFlow_1y0amk9" sourceRef="ServiceTask_1bez5fk" targetRef="EndEvent_090sn33"/><textAnnotation id="TextAnnotation_1kxxiyt"><text>Start your workflow here</text></textAnnotation><association id="Association_1seuj48" sourceRef="StartEvent_155asxm" targetRef="TextAnnotation_1kxxiyt"/><textAnnotation id="TextAnnotation_0ztsfom"><text><![CDATA[The splunk delete threat intel item function. This takes a threat type and an item key\n]]></text></textAnnotation><association id="Association_0ubek16" sourceRef="ServiceTask_1bez5fk" targetRef="TextAnnotation_0ztsfom"/></process><bpmndi:BPMNDiagram id="BPMNDiagram_1"><bpmndi:BPMNPlane bpmnElement="undefined" id="BPMNPlane_1"><bpmndi:BPMNShape bpmnElement="StartEvent_155asxm" id="StartEvent_155asxm_di"><omgdc:Bounds height="36" width="36" x="183" y="186"/><bpmndi:BPMNLabel><omgdc:Bounds height="0" width="90" x="178" y="221"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNShape bpmnElement="TextAnnotation_1kxxiyt" id="TextAnnotation_1kxxiyt_di"><omgdc:Bounds height="30" width="100" x="99" y="254"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="Association_1seuj48" id="Association_1seuj48_di"><omgdi:waypoint x="188" xsi:type="omgdc:Point" y="216"/><omgdi:waypoint x="158" xsi:type="omgdc:Point" y="254"/></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="ServiceTask_1bez5fk" id="ServiceTask_1bez5fk_di"><omgdc:Bounds height="80" width="100" x="273" y="164"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_1te3lq4" id="SequenceFlow_1te3lq4_di"><omgdi:waypoint x="219" xsi:type="omgdc:Point" y="204"/><omgdi:waypoint x="273" xsi:type="omgdc:Point" y="204"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="246" y="182"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="EndEvent_090sn33" id="EndEvent_090sn33_di"><omgdc:Bounds height="36" width="36" x="464" y="186"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="482" y="225"/></bpmndi:BPMNLabel></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="SequenceFlow_1y0amk9" id="SequenceFlow_1y0amk9_di"><omgdi:waypoint x="373" xsi:type="omgdc:Point" y="204"/><omgdi:waypoint x="464" xsi:type="omgdc:Point" y="204"/><bpmndi:BPMNLabel><omgdc:Bounds height="13" width="0" x="418.5" y="182"/></bpmndi:BPMNLabel></bpmndi:BPMNEdge><bpmndi:BPMNShape bpmnElement="TextAnnotation_0ztsfom" id="TextAnnotation_0ztsfom_di"><omgdc:Bounds height="30" width="427" x="244" y="88"/></bpmndi:BPMNShape><bpmndi:BPMNEdge bpmnElement="Association_0ubek16" id="Association_0ubek16_di"><omgdi:waypoint x="369" xsi:type="omgdc:Point" y="170"/><omgdi:waypoint x="438" xsi:type="omgdc:Point" y="118"/></bpmndi:BPMNEdge></bpmndi:BPMNPlane></bpmndi:BPMNDiagram></definitions>'},
  'object_type': 'splunk_ip_intel',
  'programmatic_name': 'delete_splunk_es_threat_intel_item'}
    )

