# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for abc"""

from __future__ import print_function
from resilient import ImportDefinition

def codegen_reload_data():
    """Parameters to codegen used to generate the package"""
    reload_params = {"package": u"rc_data_feed_plugin_resilient",
                    "incident_fields": [u"df_inc_id", u"df_org_id"],
                    "action_fields": [],
                    "functions_params": [],
                    "datatables": [],
                    "message_destinations": [],
                    "functions": [],
                    "phases": [],
                    "automatic_tasks": [],
                    "scripts": [],
                    "workflows": [],
                    "actions": [],
                    "incident_artifact_types": []
                    }
    return reload_params


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:
    #   Incident fields:
    #     df_inc_id
    #     df_org_id
    #   DataTables:
    #     data_feeder_sync


    yield ImportDefinition(u"""
eyJhY3Rpb25fb3JkZXIiOiBbXSwgImFjdGlvbnMiOiBbXSwgImF1dG9tYXRpY190YXNrcyI6IFtd
LCAiZXhwb3J0X2RhdGUiOiAxNTgzNzEzMDUxNzM0LCAiZXhwb3J0X2Zvcm1hdF92ZXJzaW9uIjog
MiwgImZpZWxkcyI6IFt7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5rX29wdGlv
biI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUsICJjaG9z
ZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVwcmVjYXRl
ZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9kZl9pbmNfaWQiLCAiaGlkZV9ub3Rp
ZmljYXRpb24iOiBmYWxzZSwgImlkIjogMTQ1MSwgImlucHV0X3R5cGUiOiAibnVtYmVyIiwgImlu
dGVybmFsIjogZmFsc2UsICJuYW1lIjogImRmX2luY19pZCIsICJvcGVyYXRpb25fcGVybXMiOiB7
fSwgIm9wZXJhdGlvbnMiOiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJvcGVy
dGllcyIsICJyZWFkX29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6IFtd
LCAidGVtcGxhdGVzIjogW10sICJ0ZXh0IjogIkRhdGEgRmVlZGVyIFN5bmMgSW5jaWRlbnQgSWQi
LCAidG9vbHRpcCI6ICJEYXRhIEZlZWRlciBTeW5jIE9yaWdpbmF0aW5nIEluY2lkZW50IElkIiwg
InR5cGVfaWQiOiAwLCAidXVpZCI6ICJhNWY3YTYzNy0wZDIzLTQ2M2EtYjhjMi05YTM3Y2FiNDY3
ODciLCAidmFsdWVzIjogW119LCB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5r
X29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUs
ICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVw
cmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9kZl9vcmdfaWQiLCAiaGlk
ZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlkIjogMTQ1MiwgImlucHV0X3R5cGUiOiAibnVtYmVy
IiwgImludGVybmFsIjogZmFsc2UsICJuYW1lIjogImRmX29yZ19pZCIsICJvcGVyYXRpb25fcGVy
bXMiOiB7fSwgIm9wZXJhdGlvbnMiOiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAi
cHJvcGVydGllcyIsICJyZWFkX29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFn
cyI6IFtdLCAidGVtcGxhdGVzIjogW10sICJ0ZXh0IjogIkRhdGEgRmVlZGVyIFN5bmMgT3JnIElk
IiwgInRvb2x0aXAiOiAiRGF0YSBGZWVkZXIgU3luYyBPcmlnaW5hdGluZyBPcmcgSWQiLCAidHlw
ZV9pZCI6IDAsICJ1dWlkIjogImFiNjJhZTdlLTdjZjItNDdiNC04OTQwLWYwZTFlMTNhNTgzNCIs
ICJ2YWx1ZXMiOiBbXX1dLCAiZnVuY3Rpb25zIjogW10sICJnZW9zIjogbnVsbCwgImdyb3VwcyI6
IG51bGwsICJpZCI6IDYzLCAiaW5ib3VuZF9tYWlsYm94ZXMiOiBudWxsLCAiaW5jaWRlbnRfYXJ0
aWZhY3RfdHlwZXMiOiBbXSwgImluY2lkZW50X3R5cGVzIjogW3sidXBkYXRlX2RhdGUiOiAxNTgz
NzEzMDUzMDc5LCAiY3JlYXRlX2RhdGUiOiAxNTgzNzEzMDUzMDc5LCAidXVpZCI6ICJiZmVlYzJk
NC0zNzcwLTExZTgtYWQzOS00YTAwMDQwNDRhYTAiLCAiZGVzY3JpcHRpb24iOiAiQ3VzdG9taXph
dGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgImV4cG9ydF9rZXkiOiAiQ3VzdG9taXphdGlvbiBQ
YWNrYWdlcyAoaW50ZXJuYWwpIiwgIm5hbWUiOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50
ZXJuYWwpIiwgImVuYWJsZWQiOiBmYWxzZSwgInN5c3RlbSI6IGZhbHNlLCAicGFyZW50X2lkIjog
bnVsbCwgImhpZGRlbiI6IGZhbHNlLCAiaWQiOiAwfV0sICJpbmR1c3RyaWVzIjogbnVsbCwgImxh
eW91dHMiOiBbXSwgImxvY2FsZSI6IG51bGwsICJtZXNzYWdlX2Rlc3RpbmF0aW9ucyI6IFtdLCAi
bm90aWZpY2F0aW9ucyI6IG51bGwsICJvdmVycmlkZXMiOiBbXSwgInBoYXNlcyI6IFtdLCAicmVn
dWxhdG9ycyI6IG51bGwsICJyb2xlcyI6IFtdLCAic2NyaXB0cyI6IFtdLCAic2VydmVyX3ZlcnNp
b24iOiB7ImJ1aWxkX251bWJlciI6IDUwODcsICJtYWpvciI6IDMzLCAibWlub3IiOiAwLCAidmVy
c2lvbiI6ICIzMy4wLjUwODcifSwgInRhZ3MiOiBbXSwgInRhc2tfb3JkZXIiOiBbXSwgInRpbWVm
cmFtZXMiOiBudWxsLCAidHlwZXMiOiBbeyJhY3Rpb25zIjogW10sICJkaXNwbGF5X25hbWUiOiAi
RGF0YSBGZWVkZXIgU3luYyIsICJleHBvcnRfa2V5IjogImRhdGFfZmVlZGVyX3N5bmMiLCAiZmll
bGRzIjogeyJuZXdfaWQiOiB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5rX29w
dGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUsICJj
aG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVwcmVj
YXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJkYXRhX2ZlZWRlcl9zeW5jL25ld19pZCIsICJo
aWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAxMzUyLCAiaW5wdXRfdHlwZSI6ICJudW1i
ZXIiLCAiaW50ZXJuYWwiOiBmYWxzZSwgIm5hbWUiOiAibmV3X2lkIiwgIm9wZXJhdGlvbl9wZXJt
cyI6IHt9LCAib3BlcmF0aW9ucyI6IFtdLCAib3JkZXIiOiAxLCAicGxhY2Vob2xkZXIiOiAiIiwg
InByZWZpeCI6IG51bGwsICJyZWFkX29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAi
dGFncyI6IFtdLCAidGVtcGxhdGVzIjogW10sICJ0ZXh0IjogIk5ldyBJZCIsICJ0b29sdGlwIjog
Im5ldyB0eXBlX2lkIGZvciBtYXBwZWQgdHlwZSIsICJ0eXBlX2lkIjogMTAyNywgInV1aWQiOiAi
ZTExMmY2MGUtNDVkYy00NDUzLTkwZjctY2Y5MDc1MmM3YjI5IiwgInZhbHVlcyI6IFtdLCAid2lk
dGgiOiA1MX0sICJsYXN0X3N5bmMiOiB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJs
YW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRy
dWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAi
ZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJkYXRhX2ZlZWRlcl9zeW5jL2xhc3Rf
c3luYyIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAxMzUzLCAiaW5wdXRfdHlw
ZSI6ICJkYXRldGltZXBpY2tlciIsICJpbnRlcm5hbCI6IGZhbHNlLCAibmFtZSI6ICJsYXN0X3N5
bmMiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25zIjogW10sICJvcmRlciI6IDIs
ICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogbnVsbCwgInJlYWRfb25seSI6IGZhbHNlLCAi
cmljaF90ZXh0IjogZmFsc2UsICJ0YWdzIjogW10sICJ0ZW1wbGF0ZXMiOiBbXSwgInRleHQiOiAi
TGFzdCBTeW5jIiwgInRvb2x0aXAiOiAiIiwgInR5cGVfaWQiOiAxMDI3LCAidXVpZCI6ICIzMjk5
MmI1Mi03NWE0LTQ4NDgtOTRlYS05MWJkNzExZGFjZGQiLCAidmFsdWVzIjogW10sICJ3aWR0aCI6
IDI3Mn0sICJrZXkiOiB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5rX29wdGlv
biI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUsICJjaG9z
ZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVwcmVjYXRl
ZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJkYXRhX2ZlZWRlcl9zeW5jL2tleSIsICJoaWRlX25v
dGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAxMzU4LCAiaW5wdXRfdHlwZSI6ICJ0ZXh0IiwgImlu
dGVybmFsIjogZmFsc2UsICJuYW1lIjogImtleSIsICJvcGVyYXRpb25fcGVybXMiOiB7fSwgIm9w
ZXJhdGlvbnMiOiBbXSwgIm9yZGVyIjogMCwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiBu
dWxsLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwg
InRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJLZXkiLCAidG9vbHRpcCI6ICI8b3JnX2lkPjo8aW5j
X2lkPjo8dHlwZV9uYW1lPjo8dHlwZV9pZD4iLCAidHlwZV9pZCI6IDEwMjcsICJ1dWlkIjogImIy
ZmQwMGY3LWQxNDAtNGU5Ny1iNWUzLTY5YWZlZGZkMjE4MyIsICJ2YWx1ZXMiOiBbXSwgIndpZHRo
IjogMzE1fX0sICJmb3JfYWN0aW9ucyI6IGZhbHNlLCAiZm9yX2N1c3RvbV9maWVsZHMiOiBmYWxz
ZSwgImZvcl9ub3RpZmljYXRpb25zIjogZmFsc2UsICJmb3Jfd29ya2Zsb3dzIjogZmFsc2UsICJp
ZCI6IG51bGwsICJwYXJlbnRfdHlwZXMiOiBbImluY2lkZW50Il0sICJwcm9wZXJ0aWVzIjogeyJj
YW5fY3JlYXRlIjogZmFsc2UsICJjYW5fZGVzdHJveSI6IGZhbHNlLCAiZm9yX3dobyI6IFtdfSwg
InNjcmlwdHMiOiBbXSwgInRhZ3MiOiBbXSwgInR5cGVfaWQiOiA4LCAidHlwZV9uYW1lIjogImRh
dGFfZmVlZGVyX3N5bmMiLCAidXVpZCI6ICIyNWM1NjNlOC0yNjFlLTQ4NDItYWU0My04YTljNGZm
NjExYTAifV0sICJ3b3JrZmxvd3MiOiBbXSwgIndvcmtzcGFjZXMiOiBbXX0=
"""
    )