# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for ibm_cloud_services"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:
    #   Function inputs:
    #     action_name
    #     application_name
    #   Message Destinations:
    #     ibm_cloud
    #   Functions:
    #     bx_cf_app_service


    yield ImportDefinition(u"""
eyJ0YXNrX29yZGVyIjogW10sICJ3b3JrZmxvd3MiOiBbXSwgImFjdGlvbnMiOiBbXSwgImxheW91
dHMiOiBudWxsLCAiZXhwb3J0X2Zvcm1hdF92ZXJzaW9uIjogMiwgImlkIjogMywgImluZHVzdHJp
ZXMiOiBudWxsLCAicGhhc2VzIjogW10sICJhY3Rpb25fb3JkZXIiOiBbXSwgImdlb3MiOiBudWxs
LCAic2VydmVyX3ZlcnNpb24iOiB7Im1ham9yIjogMzAsICJ2ZXJzaW9uIjogIjMwLjAuMCIsICJi
dWlsZF9udW1iZXIiOiAwLCAibWlub3IiOiAwfSwgInRpbWVmcmFtZXMiOiBudWxsLCAid29ya3Nw
YWNlcyI6IFtdLCAiYXV0b21hdGljX3Rhc2tzIjogW10sICJmdW5jdGlvbnMiOiBbeyJkaXNwbGF5
X25hbWUiOiAiQmx1ZW1peCBBcHBsaWNhdGlvbiBTZXJ2aWNlIiwgInV1aWQiOiAiMDdlNDBkYTUt
MjljMi00NDEzLWE4NjQtZWM4ZmEyMDY4Nzk4IiwgImNyZWF0b3IiOiB7ImRpc3BsYXlfbmFtZSI6
ICJNdWRkeSBBZG1pbiIsICJ0eXBlIjogInVzZXIiLCAiaWQiOiAxLCAibmFtZSI6ICJhZG1pbkBj
bzNzeXMuY29tIn0sICJ2aWV3X2l0ZW1zIjogW3sic2hvd19pZiI6IG51bGwsICJmaWVsZF90eXBl
IjogIl9fZnVuY3Rpb24iLCAic2hvd19saW5rX2hlYWRlciI6IGZhbHNlLCAiZWxlbWVudCI6ICJm
aWVsZF91dWlkIiwgImNvbnRlbnQiOiAiNjY1NjljMDQtMzQ0OC00MTI5LWJjMjMtYTZlYjk0YzA3
Yzk5IiwgInN0ZXBfbGFiZWwiOiBudWxsfSwgeyJzaG93X2lmIjogbnVsbCwgImZpZWxkX3R5cGUi
OiAiX19mdW5jdGlvbiIsICJzaG93X2xpbmtfaGVhZGVyIjogZmFsc2UsICJlbGVtZW50IjogImZp
ZWxkX3V1aWQiLCAiY29udGVudCI6ICJlOWJmZDRjNy1kMjBhLTQ3YzYtYWNlOS1hODhmNzkyMDk3
ZGUiLCAic3RlcF9sYWJlbCI6IG51bGx9XSwgImV4cG9ydF9rZXkiOiAiYnhfY2ZfYXBwX3NlcnZp
Y2UiLCAibGFzdF9tb2RpZmllZF9ieSI6IHsiZGlzcGxheV9uYW1lIjogIk11ZGR5IEFkbWluIiwg
InR5cGUiOiAidXNlciIsICJpZCI6IDEsICJuYW1lIjogImFkbWluQGNvM3N5cy5jb20ifSwgIm5h
bWUiOiAiYnhfY2ZfYXBwX3NlcnZpY2UiLCAidmVyc2lvbiI6IDAsICJ3b3JrZmxvd3MiOiBbeyJw
cm9ncmFtbWF0aWNfbmFtZSI6ICJieF9mbl93ayIsICJvYmplY3RfdHlwZSI6ICJpbmNpZGVudCIs
ICJ1dWlkIjogbnVsbCwgImFjdGlvbnMiOiBbXSwgIm5hbWUiOiAiYnhfZm5fd2siLCAid29ya2Zs
b3dfaWQiOiAyNTcsICJkZXNjcmlwdGlvbiI6IG51bGx9XSwgImxhc3RfbW9kaWZpZWRfdGltZSI6
IDE1MjUxMDY3NDk0MDEsICJkZXN0aW5hdGlvbl9oYW5kbGUiOiAiaWJtX2Nsb3VkIiwgImlkIjog
MjgsICJkZXNjcmlwdGlvbiI6IHsiY29udGVudCI6ICIiLCAiZm9ybWF0IjogInRleHQifX1dLCAi
bm90aWZpY2F0aW9ucyI6IG51bGwsICJyZWd1bGF0b3JzIjogbnVsbCwgImluY2lkZW50X3R5cGVz
IjogW3siY3JlYXRlX2RhdGUiOiAxNTI1MTA3MjMyMTkwLCAiZGVzY3JpcHRpb24iOiAiQ3VzdG9t
aXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgImV4cG9ydF9rZXkiOiAiQ3VzdG9taXphdGlv
biBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgImlkIjogMCwgIm5hbWUiOiAiQ3VzdG9taXphdGlvbiBQ
YWNrYWdlcyAoaW50ZXJuYWwpIiwgInVwZGF0ZV9kYXRlIjogMTUyNTEwNzIzMjE5MCwgInV1aWQi
OiAiYmZlZWMyZDQtMzc3MC0xMWU4LWFkMzktNGEwMDA0MDQ0YWEwIiwgImVuYWJsZWQiOiBmYWxz
ZSwgInN5c3RlbSI6IGZhbHNlLCAicGFyZW50X2lkIjogbnVsbCwgImhpZGRlbiI6IGZhbHNlfV0s
ICJzY3JpcHRzIjogW10sICJ0eXBlcyI6IFtdLCAibWVzc2FnZV9kZXN0aW5hdGlvbnMiOiBbeyJ1
dWlkIjogIjE5MmZhZDMyLTNhZjktNDZjYy04MDI2LTQzNjQ5MGM0OGI5YyIsICJleHBvcnRfa2V5
IjogImlibV9jbG91ZCIsICJuYW1lIjogIklCTSBDbG91ZCIsICJkZXN0aW5hdGlvbl90eXBlIjog
MCwgInByb2dyYW1tYXRpY19uYW1lIjogImlibV9jbG91ZCIsICJleHBlY3RfYWNrIjogdHJ1ZSwg
InVzZXJzIjogWyJhZG1pbkBjbzNzeXMuY29tIl19XSwgImluY2lkZW50X2FydGlmYWN0X3R5cGVz
IjogW10sICJyb2xlcyI6IFtdLCAiZmllbGRzIjogW3sib3BlcmF0aW9ucyI6IFtdLCAicmVhZF9v
bmx5IjogdHJ1ZSwgInV1aWQiOiAiYzNmMGUzZWQtMjFlMS00ZDUzLWFmZmItZmU1Y2EzMzA4Y2Nh
IiwgInRlbXBsYXRlcyI6IFtdLCAidHlwZV9pZCI6IDAsICJjaG9zZW4iOiBmYWxzZSwgInRleHQi
OiAiU2ltdWxhdGlvbiIsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgImV4cG9y
dF9rZXkiOiAiaW5jaWRlbnQvaW5jX3RyYWluaW5nIiwgInRvb2x0aXAiOiAiV2hldGhlciB0aGUg
aW5jaWRlbnQgaXMgYSBzaW11bGF0aW9uIG9yIGEgcmVndWxhciBpbmNpZGVudC4gIFRoaXMgZmll
bGQgaXMgcmVhZC1vbmx5LiIsICJyaWNoX3RleHQiOiBmYWxzZSwgIm9wZXJhdGlvbl9wZXJtcyI6
IHt9LCAicHJlZml4IjogbnVsbCwgImludGVybmFsIjogZmFsc2UsICJ2YWx1ZXMiOiBbXSwgImJs
YW5rX29wdGlvbiI6IGZhbHNlLCAiaW5wdXRfdHlwZSI6ICJib29sZWFuIiwgImNoYW5nZWFibGUi
OiB0cnVlLCAiaGlkZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlkIjogMzgsICJuYW1lIjogImlu
Y190cmFpbmluZyJ9LCB7Im9wZXJhdGlvbnMiOiBbXSwgInR5cGVfaWQiOiAxMSwgIm9wZXJhdGlv
bl9wZXJtcyI6IHt9LCAidGV4dCI6ICJhY3Rpb25fbmFtZSIsICJibGFua19vcHRpb24iOiBmYWxz
ZSwgInByZWZpeCI6IG51bGwsICJjaGFuZ2VhYmxlIjogdHJ1ZSwgImlkIjogOTU0LCAicmVhZF9v
bmx5IjogZmFsc2UsICJ1dWlkIjogImU5YmZkNGM3LWQyMGEtNDdjNi1hY2U5LWE4OGY3OTIwOTdk
ZSIsICJjaG9zZW4iOiBmYWxzZSwgImlucHV0X3R5cGUiOiAidGV4dCIsICJ0b29sdGlwIjogIiIs
ICJpbnRlcm5hbCI6IGZhbHNlLCAicmljaF90ZXh0IjogZmFsc2UsICJ0ZW1wbGF0ZXMiOiBbXSwg
ImV4cG9ydF9rZXkiOiAiX19mdW5jdGlvbi9hY3Rpb25fbmFtZSIsICJoaWRlX25vdGlmaWNhdGlv
biI6IGZhbHNlLCAicGxhY2Vob2xkZXIiOiAiIiwgIm5hbWUiOiAiYWN0aW9uX25hbWUiLCAiZGVm
YXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2UsICJ2YWx1ZXMiOiBbXX0sIHsib3BlcmF0aW9u
cyI6IFtdLCAidHlwZV9pZCI6IDExLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJ0ZXh0IjogImFw
cGxpY2F0aW9uX25hbWUiLCAiYmxhbmtfb3B0aW9uIjogZmFsc2UsICJwcmVmaXgiOiBudWxsLCAi
Y2hhbmdlYWJsZSI6IHRydWUsICJpZCI6IDk1MywgInJlYWRfb25seSI6IGZhbHNlLCAidXVpZCI6
ICI2NjU2OWMwNC0zNDQ4LTQxMjktYmMyMy1hNmViOTRjMDdjOTkiLCAiY2hvc2VuIjogZmFsc2Us
ICJpbnB1dF90eXBlIjogInRleHQiLCAidG9vbHRpcCI6ICIiLCAiaW50ZXJuYWwiOiBmYWxzZSwg
InJpY2hfdGV4dCI6IGZhbHNlLCAidGVtcGxhdGVzIjogW10sICJleHBvcnRfa2V5IjogIl9fZnVu
Y3Rpb24vYXBwbGljYXRpb25fbmFtZSIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAicGxh
Y2Vob2xkZXIiOiAiIiwgIm5hbWUiOiAiYXBwbGljYXRpb25fbmFtZSIsICJkZWZhdWx0X2Nob3Nl
bl9ieV9zZXJ2ZXIiOiBmYWxzZSwgInZhbHVlcyI6IFtdfV0sICJvdmVycmlkZXMiOiBbXSwgImV4
cG9ydF9kYXRlIjogMTUyNTEwNjk1NDE1Mn0=
"""
    )
