# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fun_utilities"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # Function-field definitions
    yield TypeDefinition(
        {
            "type_name": "__function",
            "fields": { 'artifact_file_type': { 'blank_option': False,
                          'input_type': 'select',
                          'name': 'artifact_file_type',
                          'placeholder': '',
                          'rich_text': False,
                          'templates': [],
                          'text': 'artifact_file_type',
                          'tooltip': '',
                          'uuid': '247c1025-f582-4641-9ce6-5da976797e50',
                          'values': [ { 'label': 'Email Attachment'},
                                      { 'label': 'Malware Sample'},
                                      { 'label': 'Log File'},
                                      { 'label': 'X509 Certificate File'},
                                      { 'label': 'RFC 822 Email Message File'},
                                      { 'label': 'Other File'}]},
  'artifact_id': { 'blank_option': False,
                   'input_type': 'number',
                   'name': 'artifact_id',
                   'placeholder': '',
                   'rich_text': False,
                   'templates': [],
                   'text': 'artifact_id',
                   'tooltip': '',
                   'uuid': '504acd04-c60b-4b72-8a76-6e04d48daf1c',
                   'values': []},
  'attachment_id': { 'blank_option': False,
                     'input_type': 'number',
                     'name': 'attachment_id',
                     'placeholder': '',
                     'rich_text': False,
                     'templates': [],
                     'text': 'attachment_id',
                     'tooltip': '',
                     'uuid': '17c3e652-6559-4935-9f95-74374ca37a7b',
                     'values': []},
  'base64content': { 'blank_option': False,
                     'input_type': 'text',
                     'name': 'base64content',
                     'placeholder': '',
                     'rich_text': False,
                     'templates': [],
                     'text': 'base64content',
                     'tooltip': '',
                     'uuid': 'eabbb71e-334b-4765-b143-3dc3427ba273',
                     'values': []},
  'content_type': { 'blank_option': False,
                    'input_type': 'text',
                    'name': 'content_type',
                    'placeholder': '',
                    'rich_text': False,
                    'templates': [],
                    'text': 'content_type',
                    'tooltip': '',
                    'uuid': 'ae9b660d-a66b-4a4e-b216-9aa53f747c89',
                    'values': []},
  'description': { 'blank_option': False,
                   'input_type': 'textarea',
                   'name': 'description',
                   'placeholder': '',
                   'rich_text': False,
                   'templates': [],
                   'text': 'description',
                   'tooltip': '',
                   'uuid': '3c82d51d-265f-464c-aac4-57de599cea8a',
                   'values': []},
  'file_name': { 'blank_option': False,
                 'input_type': 'text',
                 'name': 'file_name',
                 'placeholder': '',
                 'rich_text': False,
                 'templates': [],
                 'text': 'file_name',
                 'tooltip': '',
                 'uuid': '0c493e99-1135-4bea-9709-3aafbc492399',
                 'values': []},
  'file_path': { 'blank_option': False,
                 'input_type': 'text',
                 'name': 'file_path',
                 'placeholder': '',
                 'rich_text': False,
                 'templates': [],
                 'text': 'file_path',
                 'tooltip': '',
                 'uuid': 'f9633eec-4afe-4e09-bd9a-8f63a45c55f0',
                 'values': []},
  'incident_id': { 'blank_option': False,
                   'input_type': 'number',
                   'name': 'incident_id',
                   'placeholder': '',
                   'rich_text': False,
                   'templates': [],
                   'text': 'incident_id',
                   'tooltip': '',
                   'uuid': 'ead214c2-13fe-43f6-a3c7-676a88338dbb',
                   'values': []},
  'seconds': { 'blank_option': False,
               'input_type': 'number',
               'name': 'seconds',
               'placeholder': '',
               'rich_text': False,
               'templates': [],
               'text': 'seconds',
               'tooltip': '',
               'uuid': '79cee9ba-be43-4934-997d-c66baf7da81c',
               'values': []},
  'task_id': { 'blank_option': False,
               'input_type': 'number',
               'name': 'task_id',
               'placeholder': '',
               'rich_text': False,
               'templates': [],
               'text': 'task_id',
               'tooltip': '',
               'uuid': 'f934cf75-e9f3-4d1c-bf64-9e4f66f16d7f',
               'values': []},
  'zipfile_password': { 'blank_option': False,
                        'input_type': 'text',
                        'name': 'zipfile_password',
                        'placeholder': '',
                        'rich_text': False,
                        'templates': [],
                        'text': 'zipfile_password',
                        'tooltip': '',
                        'uuid': '9ab219d3-d31e-407c-9cbb-a07c76c649a1',
                        'values': []}}
        }
    )

    # Message destination: 'fun_utilities'
    yield MessageDestinationDefinition({ 'destination_type': 0,
  'expect_ack': True,
  'name': 'fun_utilities',
  'programmatic_name': 'fun_utilities'}
    )

    # Function: 'base64_to_artifact'
    yield FunctionDefinition({ 'description': { 'content': 'Create a new artifact from a Base64 string',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Base64 to Artifact',
  'name': 'base64_to_artifact',
  'uuid': 'e82fa06a-584c-4f8d-9429-448ddc3d8bc4',
  'view_items': [ { 'content': 'base64content',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'artifact_file_type',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'file_name',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'content_type',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'description',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'attachment_move_to_artifact'
    yield FunctionDefinition({ 'description': { 'content': 'Move an Attachment to an Artifact.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Attachment Move to Artifact',
  'name': 'attachment_move_to_artifact',
  'uuid': 'b0332700-fb72-4a32-bc9f-2e1291170204',
  'view_items': [ { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'task_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'attachment_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'artifact_file_type',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'description',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'base64_to_attachment'
    yield FunctionDefinition({ 'description': { 'content': 'Create a new attachment fro base64 string.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Base64 to Attachment',
  'name': 'base64_to_attachment',
  'uuid': '11349159-153e-49b7-9a9b-e22676c03687',
  'view_items': [ { 'content': 'base64content',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'task_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'file_name',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'content_type',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'attachment_zip_extract'
    yield FunctionDefinition({ 'description': { 'content': 'Extract a file from a zipfile attachment, producing a base64 string.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Attachment Zip Extract',
  'name': 'attachment_zip_extract',
  'uuid': '4d9fb1df-1eab-494b-8375-c4feb0525429',
  'view_items': [ { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'task_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'attachment_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'file_path',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'zipfile_password',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'attachment_zip_list'
    yield FunctionDefinition({ 'description': { 'content': 'For a zipfile attachment, return a list of its contents.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Attachment Zip List',
  'name': 'attachment_zip_list',
  'uuid': 'c28c15ac-ecd2-4cd8-ba85-8f8c2bb307d2',
  'view_items': [ { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'task_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'attachment_id',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'attachment_hash'
    yield FunctionDefinition({ 'description': { 'content': 'Calculate hashes for a file attachment.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Attachment Hash',
  'name': 'attachment_hash',
  'uuid': '9e0f46f4-ae8c-4aa6-a296-3a0662a53386',
  'view_items': [ { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'task_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'attachment_id',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'wait'
    yield FunctionDefinition({ 'description': { 'content': 'Waits for a given number of seconds',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Wait',
  'name': 'wait',
  'uuid': 'f17025e5-5437-477f-b7ce-6d1f38a67cac',
  'view_items': [ { 'content': 'seconds',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'attachment_to_base64'
    yield FunctionDefinition({ 'description': { 'content': 'Read a file attachment as a Base64 string.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Attachment to Base64',
  'name': 'attachment_to_base64',
  'uuid': '3a4b66c4-0465-4960-8bbf-fa3ebdc58c5a',
  'view_items': [ { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'task_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'attachment_id',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

    # Function: 'artifact_email_parse'
    yield FunctionDefinition({ 'description': { 'content': 'Extract message headers and body parts from an email message artifact.',
                   'format': 'text'},
  'destination_handle': 'fun_utilities',
  'display_name': 'Artifact Email Parse',
  'name': 'artifact_email_parse',
  'uuid': 'd83f571e-8904-4123-9c2c-3f404b00cc5e',
  'view_items': [ { 'content': 'incident_id',
                    'element': 'field',
                    'field_type': '__function'},
                  { 'content': 'artifact_id',
                    'element': 'field',
                    'field_type': '__function'}]}
    )

