echo "Start..."

# resilient-circuits clone --workflow example_sn_utilities_add_attachment_to_servicenow_record example_snow_add_attachment_to_record
# resilient-circuits clone --workflow example_sn_utilities_add_comment_to_servicenow_record example_snow_add_comment_to_record
# resilient-circuits clone --workflow example_sn_utilities_add_work_note_to_servicenow_record example_snow_add_worknote_to_record
# resilient-circuits clone --workflow example_sn_utilities_close_incident_in_servicenow example_snow_close_record_incident


# resilient-circuits clone --workflow example_sn_utilities_update_datatable_incident_status_change example_snow_update_datatable_on_status_change_incident
# resilient-circuits clone --workflow example_sn_utilities_update_datatable_task_status_change example_snow_update_datatable_on_status_change_task

resilient-circuits clone --workflow example_sn_utilities_close_task_in_servicenow example_snow_close_record_task
# resilient-circuits clone --workflow example_sn_utilities_close_incident_in_servicenow example_snow_close_record_incident

resilient-circuits clone --workflow example_sn_utilities_create_incident_in_servicenow example_snow_create_record_incident
resilient-circuits clone --workflow example_sn_utilities_create_task_in_servicenow example_snow_create_record_task

echo "Finish..."
