# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_mcafee_esm"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:
    #   Message Destinations:
    #     mcafee_esm_message_destination
    #   Functions:
    #     mcafee_esm_get_case_details


    yield ImportDefinition(u"""
eyJ0YXNrX29yZGVyIjogW10sICJ3b3JrZmxvd3MiOiBbXSwgImFjdGlvbnMiOiBbXSwgImxheW91
dHMiOiBbXSwgImV4cG9ydF9mb3JtYXRfdmVyc2lvbiI6IDIsICJpZCI6IDksICJpbmR1c3RyaWVz
IjogbnVsbCwgInBoYXNlcyI6IFtdLCAiYWN0aW9uX29yZGVyIjogW10sICJnZW9zIjogbnVsbCwg
InNlcnZlcl92ZXJzaW9uIjogeyJtYWpvciI6IDMwLCAidmVyc2lvbiI6ICIzMC4wLjM0NzYiLCAi
YnVpbGRfbnVtYmVyIjogMzQ3NiwgIm1pbm9yIjogMH0sICJ0aW1lZnJhbWVzIjogbnVsbCwgIndv
cmtzcGFjZXMiOiBbXSwgImF1dG9tYXRpY190YXNrcyI6IFtdLCAiZnVuY3Rpb25zIjogW3siZGlz
cGxheV9uYW1lIjogIk1jQWZlZSBFU00gZ2V0IGNhc2UgZGV0YWlscyIsICJ1dWlkIjogIjVjMDMz
OWMyLWUyYmUtNDZkMy1hMjgzLTJjOTNlZGMwZTA5ZiIsICJjcmVhdG9yIjogeyJkaXNwbGF5X25h
bWUiOiAiUmVzaWxpZW50IFN5c2FkbWluIiwgInR5cGUiOiAidXNlciIsICJpZCI6IDEsICJuYW1l
IjogImFkbWluQGNvM3N5cy5jb20ifSwgInZpZXdfaXRlbXMiOiBbXSwgImV4cG9ydF9rZXkiOiAi
bWNhZmVlX2VzbV9nZXRfY2FzZV9kZXRhaWxzIiwgImxhc3RfbW9kaWZpZWRfYnkiOiB7ImRpc3Bs
YXlfbmFtZSI6ICJSZXNpbGllbnQgU3lzYWRtaW4iLCAidHlwZSI6ICJ1c2VyIiwgImlkIjogMSwg
Im5hbWUiOiAiYWRtaW5AY28zc3lzLmNvbSJ9LCAibmFtZSI6ICJtY2FmZWVfZXNtX2dldF9jYXNl
X2RldGFpbHMiLCAidmVyc2lvbiI6IDAsICJ3b3JrZmxvd3MiOiBbXSwgImxhc3RfbW9kaWZpZWRf
dGltZSI6IDE1MzE4NjUwMzQ2MzEsICJkZXN0aW5hdGlvbl9oYW5kbGUiOiAibWNhZmVlX2VzbV9t
ZXNzYWdlX2Rlc3RpbmF0aW9uIiwgImlkIjogMTAsICJkZXNjcmlwdGlvbiI6IHsiY29udGVudCI6
ICIiLCAiZm9ybWF0IjogInRleHQifX1dLCAibm90aWZpY2F0aW9ucyI6IG51bGwsICJyZWd1bGF0
b3JzIjogbnVsbCwgImluY2lkZW50X3R5cGVzIjogW3siY3JlYXRlX2RhdGUiOiAxNTMyMTE2NjY0
NjY0LCAiZGVzY3JpcHRpb24iOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwg
ImV4cG9ydF9rZXkiOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgImlkIjog
MCwgIm5hbWUiOiAiQ3VzdG9taXphdGlvbiBQYWNrYWdlcyAoaW50ZXJuYWwpIiwgInVwZGF0ZV9k
YXRlIjogMTUzMjExNjY2NDY2NCwgInV1aWQiOiAiYmZlZWMyZDQtMzc3MC0xMWU4LWFkMzktNGEw
MDA0MDQ0YWEwIiwgImVuYWJsZWQiOiBmYWxzZSwgInN5c3RlbSI6IGZhbHNlLCAicGFyZW50X2lk
IjogbnVsbCwgImhpZGRlbiI6IGZhbHNlfV0sICJzY3JpcHRzIjogW10sICJ0eXBlcyI6IFtdLCAi
bWVzc2FnZV9kZXN0aW5hdGlvbnMiOiBbeyJ1dWlkIjogImIwMzBjN2UxLTI4ZGQtNDNlZS04NTUy
LTVhMzliZjBiOTdkZiIsICJleHBvcnRfa2V5IjogIm1jYWZlZV9lc21fbWVzc2FnZV9kZXN0aW5h
dGlvbiIsICJuYW1lIjogIk1jQWZlZSBFU00gTWVzc2FnZSBEZXN0aW5hdGlvbiIsICJkZXN0aW5h
dGlvbl90eXBlIjogMCwgInByb2dyYW1tYXRpY19uYW1lIjogIm1jYWZlZV9lc21fbWVzc2FnZV9k
ZXN0aW5hdGlvbiIsICJleHBlY3RfYWNrIjogdHJ1ZSwgInVzZXJzIjogWyJhZG1pbkBjbzNzeXMu
Y29tIiwgImJ3YWxzaEByZXNpbGllbnRzeXN0ZW1zLmNvbSJdfV0sICJpbmNpZGVudF9hcnRpZmFj
dF90eXBlcyI6IFtdLCAicm9sZXMiOiBbXSwgImZpZWxkcyI6IFt7Im9wZXJhdGlvbnMiOiBbXSwg
InJlYWRfb25seSI6IHRydWUsICJ1dWlkIjogImMzZjBlM2VkLTIxZTEtNGQ1My1hZmZiLWZlNWNh
MzMwOGNjYSIsICJ0ZW1wbGF0ZXMiOiBbXSwgInR5cGVfaWQiOiAwLCAiY2hvc2VuIjogZmFsc2Us
ICJ0ZXh0IjogIlNpbXVsYXRpb24iLCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2Us
ICJleHBvcnRfa2V5IjogImluY2lkZW50L2luY190cmFpbmluZyIsICJ0b29sdGlwIjogIldoZXRo
ZXIgdGhlIGluY2lkZW50IGlzIGEgc2ltdWxhdGlvbiBvciBhIHJlZ3VsYXIgaW5jaWRlbnQuICBU
aGlzIGZpZWxkIGlzIHJlYWQtb25seS4iLCAicmljaF90ZXh0IjogZmFsc2UsICJvcGVyYXRpb25f
cGVybXMiOiB7fSwgInByZWZpeCI6IG51bGwsICJpbnRlcm5hbCI6IGZhbHNlLCAidmFsdWVzIjog
W10sICJibGFua19vcHRpb24iOiBmYWxzZSwgImlucHV0X3R5cGUiOiAiYm9vbGVhbiIsICJjaGFu
Z2VhYmxlIjogdHJ1ZSwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDM4LCAibmFt
ZSI6ICJpbmNfdHJhaW5pbmcifV0sICJvdmVycmlkZXMiOiBbXSwgImV4cG9ydF9kYXRlIjogMTUz
MTg5MjYzMTA3N30=
"""
    )
