# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_thug"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:
    #   Function inputs:
    #     thug_args
    #     thug_url
    #   Message Destinations:
    #     fn_thug
    #   Functions:
    #     thug_analysis


    yield ImportDefinition(u"""
eyJ0YXNrX29yZGVyIjogW10sICJ3b3JrZmxvd3MiOiBbXSwgImFjdGlvbnMiOiBbXSwgImxheW91
dHMiOiBbXSwgImV4cG9ydF9mb3JtYXRfdmVyc2lvbiI6IDIsICJpZCI6IDEsICJpbmR1c3RyaWVz
IjogbnVsbCwgInBoYXNlcyI6IFtdLCAiYWN0aW9uX29yZGVyIjogW10sICJnZW9zIjogbnVsbCwg
InNlcnZlcl92ZXJzaW9uIjogeyJtYWpvciI6IDMxLCAidmVyc2lvbiI6ICIzMS4wLjQwMjYiLCAi
YnVpbGRfbnVtYmVyIjogNDAyNiwgIm1pbm9yIjogMH0sICJ0aW1lZnJhbWVzIjogbnVsbCwgIndv
cmtzcGFjZXMiOiBbXSwgImF1dG9tYXRpY190YXNrcyI6IFtdLCAiZnVuY3Rpb25zIjogW3siZGlz
cGxheV9uYW1lIjogIlRodWcgQW5hbHlzaXMiLCAidXVpZCI6ICJjYWI2OWFiYy04NGU5LTRhNDEt
YWUxZi0xMmE2YWU0ZGQzYzAiLCAiY3JlYXRvciI6IHsiZGlzcGxheV9uYW1lIjogIlJlc2lsaWVu
dCBTeXNhZG1pbiIsICJ0eXBlIjogInVzZXIiLCAiaWQiOiAyLCAibmFtZSI6ICJhQGEuY29tIn0s
ICJ2aWV3X2l0ZW1zIjogW3sic2hvd19pZiI6IG51bGwsICJmaWVsZF90eXBlIjogIl9fZnVuY3Rp
b24iLCAic2hvd19saW5rX2hlYWRlciI6IGZhbHNlLCAiZWxlbWVudCI6ICJmaWVsZF91dWlkIiwg
ImNvbnRlbnQiOiAiYzVjMmMzZDMtMWU1Ny00ODYxLWIxZjgtNzkxZTFiYTQwM2NjIiwgInN0ZXBf
bGFiZWwiOiBudWxsfSwgeyJzaG93X2lmIjogbnVsbCwgImZpZWxkX3R5cGUiOiAiX19mdW5jdGlv
biIsICJzaG93X2xpbmtfaGVhZGVyIjogZmFsc2UsICJlbGVtZW50IjogImZpZWxkX3V1aWQiLCAi
Y29udGVudCI6ICJmNzk5MTUzMy1mMjAyLTQwMGYtODA5YS0yZjljMDRlY2QzMmIiLCAic3RlcF9s
YWJlbCI6IG51bGx9XSwgImV4cG9ydF9rZXkiOiAidGh1Z19hbmFseXNpcyIsICJsYXN0X21vZGlm
aWVkX2J5IjogeyJkaXNwbGF5X25hbWUiOiAiUmVzaWxpZW50IFN5c2FkbWluIiwgInR5cGUiOiAi
dXNlciIsICJpZCI6IDIsICJuYW1lIjogImFAYS5jb20ifSwgIm5hbWUiOiAidGh1Z19hbmFseXNp
cyIsICJ2ZXJzaW9uIjogMCwgIndvcmtmbG93cyI6IFtdLCAibGFzdF9tb2RpZmllZF90aW1lIjog
MTUzMTgzODkxNTAzNiwgImRlc3RpbmF0aW9uX2hhbmRsZSI6ICJmbl90aHVnIiwgImlkIjogMSwg
ImRlc2NyaXB0aW9uIjogeyJjb250ZW50IjogIiIsICJmb3JtYXQiOiAidGV4dCJ9fV0sICJub3Rp
ZmljYXRpb25zIjogbnVsbCwgInJlZ3VsYXRvcnMiOiBudWxsLCAiaW5jaWRlbnRfdHlwZXMiOiBb
eyJjcmVhdGVfZGF0ZSI6IDE1MzQ4NjczMTQ5MDUsICJkZXNjcmlwdGlvbiI6ICJDdXN0b21pemF0
aW9uIFBhY2thZ2VzIChpbnRlcm5hbCkiLCAiZXhwb3J0X2tleSI6ICJDdXN0b21pemF0aW9uIFBh
Y2thZ2VzIChpbnRlcm5hbCkiLCAiaWQiOiAwLCAibmFtZSI6ICJDdXN0b21pemF0aW9uIFBhY2th
Z2VzIChpbnRlcm5hbCkiLCAidXBkYXRlX2RhdGUiOiAxNTM0ODY3MzE0OTA1LCAidXVpZCI6ICJi
ZmVlYzJkNC0zNzcwLTExZTgtYWQzOS00YTAwMDQwNDRhYTAiLCAiZW5hYmxlZCI6IGZhbHNlLCAi
c3lzdGVtIjogZmFsc2UsICJwYXJlbnRfaWQiOiBudWxsLCAiaGlkZGVuIjogZmFsc2V9XSwgInNj
cmlwdHMiOiBbXSwgInR5cGVzIjogW10sICJtZXNzYWdlX2Rlc3RpbmF0aW9ucyI6IFt7InV1aWQi
OiAiMjE4YTUxYjUtMzE4Yi00MWMwLThiZjEtNTcyYzI0MDYzMjM2IiwgImV4cG9ydF9rZXkiOiAi
Zm5fdGh1ZyIsICJuYW1lIjogImZuX3RodWciLCAiZGVzdGluYXRpb25fdHlwZSI6IDAsICJwcm9n
cmFtbWF0aWNfbmFtZSI6ICJmbl90aHVnIiwgImV4cGVjdF9hY2siOiB0cnVlLCAidXNlcnMiOiBb
ImFAYS5jb20iXX1dLCAiaW5jaWRlbnRfYXJ0aWZhY3RfdHlwZXMiOiBbXSwgInJvbGVzIjogW10s
ICJmaWVsZHMiOiBbeyJvcGVyYXRpb25zIjogW10sICJyZWFkX29ubHkiOiB0cnVlLCAidXVpZCI6
ICJjM2YwZTNlZC0yMWUxLTRkNTMtYWZmYi1mZTVjYTMzMDhjY2EiLCAidGVtcGxhdGVzIjogW10s
ICJ0eXBlX2lkIjogMCwgImNob3NlbiI6IGZhbHNlLCAidGV4dCI6ICJTaW11bGF0aW9uIiwgImRl
ZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9p
bmNfdHJhaW5pbmciLCAidG9vbHRpcCI6ICJXaGV0aGVyIHRoZSBpbmNpZGVudCBpcyBhIHNpbXVs
YXRpb24gb3IgYSByZWd1bGFyIGluY2lkZW50LiAgVGhpcyBmaWVsZCBpcyByZWFkLW9ubHkuIiwg
InJpY2hfdGV4dCI6IGZhbHNlLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJwcmVmaXgiOiBudWxs
LCAiaW50ZXJuYWwiOiBmYWxzZSwgInZhbHVlcyI6IFtdLCAiYmxhbmtfb3B0aW9uIjogZmFsc2Us
ICJpbnB1dF90eXBlIjogImJvb2xlYW4iLCAiY2hhbmdlYWJsZSI6IHRydWUsICJoaWRlX25vdGlm
aWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzOCwgIm5hbWUiOiAiaW5jX3RyYWluaW5nIn0sIHsib3Bl
cmF0aW9ucyI6IFtdLCAidHlwZV9pZCI6IDExLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJ0ZXh0
IjogInRodWdfdXJsIiwgImJsYW5rX29wdGlvbiI6IGZhbHNlLCAicHJlZml4IjogbnVsbCwgImNo
YW5nZWFibGUiOiB0cnVlLCAiaWQiOiA4NSwgInJlYWRfb25seSI6IGZhbHNlLCAidXVpZCI6ICJm
Nzk5MTUzMy1mMjAyLTQwMGYtODA5YS0yZjljMDRlY2QzMmIiLCAiY2hvc2VuIjogZmFsc2UsICJp
bnB1dF90eXBlIjogInRleHQiLCAidG9vbHRpcCI6ICIiLCAiaW50ZXJuYWwiOiBmYWxzZSwgInJp
Y2hfdGV4dCI6IGZhbHNlLCAidGVtcGxhdGVzIjogW10sICJleHBvcnRfa2V5IjogIl9fZnVuY3Rp
b24vdGh1Z191cmwiLCAiaGlkZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgInBsYWNlaG9sZGVyIjog
IiIsICJuYW1lIjogInRodWdfdXJsIiwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNl
LCAidmFsdWVzIjogW119LCB7Im9wZXJhdGlvbnMiOiBbXSwgInR5cGVfaWQiOiAxMSwgIm9wZXJh
dGlvbl9wZXJtcyI6IHt9LCAidGV4dCI6ICJ0aHVnX2FyZ3MiLCAiYmxhbmtfb3B0aW9uIjogZmFs
c2UsICJwcmVmaXgiOiBudWxsLCAiY2hhbmdlYWJsZSI6IHRydWUsICJpZCI6IDg2LCAicmVhZF9v
bmx5IjogZmFsc2UsICJ1dWlkIjogImM1YzJjM2QzLTFlNTctNDg2MS1iMWY4LTc5MWUxYmE0MDNj
YyIsICJjaG9zZW4iOiBmYWxzZSwgImlucHV0X3R5cGUiOiAidGV4dCIsICJ0b29sdGlwIjogIiIs
ICJpbnRlcm5hbCI6IGZhbHNlLCAicmljaF90ZXh0IjogZmFsc2UsICJ0ZW1wbGF0ZXMiOiBbXSwg
ImV4cG9ydF9rZXkiOiAiX19mdW5jdGlvbi90aHVnX2FyZ3MiLCAiaGlkZV9ub3RpZmljYXRpb24i
OiBmYWxzZSwgInBsYWNlaG9sZGVyIjogIiIsICJuYW1lIjogInRodWdfYXJncyIsICJkZWZhdWx0
X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgInZhbHVlcyI6IFtdfV0sICJvdmVycmlkZXMiOiBb
XSwgImV4cG9ydF9kYXRlIjogMTUzMTgzODkyNjcyNn0=
"""
    )
