# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_aws_guardduty"""

try:
    from resilient import ImportDefinition
except ImportError:
    # Support Apps running on resilient-circuits < v35.0.195
    from resilient_circuits.util import ImportDefinition


def codegen_reload_data():
    """
    Parameters required reload codegen for the fn_aws_guardduty package
    """
    return {
        "package": u"fn_aws_guardduty",
        "message_destinations": [],
        "functions": [],
        "workflows": [],
        "actions": [],
        "incident_fields": [u"aws_guardduty_region", u"aws_guardduty_finding_arn", u"aws_guardduty_count", u"aws_guardduty_finding_type", u"aws_guardduty_finding_id", u"aws_guardduty_resource_type", u"aws_guardduty_detector_id"],
        "incident_artifact_types": [u"aws_iam_access_key_id", u"aws_iam_user_name"],
        "datatables": [],
        "automatic_tasks": [],
        "scripts": []
    }


def customization_data(client=None):
    """
    Returns a Generator of ImportDefinitions (Customizations).
    Install them using `resilient-circuits customize`

    IBM Resilient Platform Version: 37.2.38

    Contents:
    - Incident Fields:
        - aws_guardduty_region
        - aws_guardduty_finding_arn
        - aws_guardduty_count
        - aws_guardduty_finding_type
        - aws_guardduty_finding_id
        - aws_guardduty_resource_type
        - aws_guardduty_detector_id
    - Custom Artifact Types:
        - aws_iam_access_key_id
        - aws_iam_user_name
    """

    yield ImportDefinition(u"""
eyJhY3Rpb25fb3JkZXIiOiBbXSwgImFjdGlvbnMiOiBbXSwgImFwcHMiOiBbXSwgImF1dG9tYXRp
Y190YXNrcyI6IFtdLCAiZXhwb3J0X2RhdGUiOiAxNjA3MDAwMjU1NzQwLCAiZXhwb3J0X2Zvcm1h
dF92ZXJzaW9uIjogMiwgImZpZWxkcyI6IFt7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwg
ImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6
IHRydWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNl
LCAiZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9hd3NfZ3VhcmRk
dXR5X3JlZ2lvbiIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzNzcsICJpbnB1
dF90eXBlIjogInRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwg
Im5hbWUiOiAiYXdzX2d1YXJkZHV0eV9yZWdpb24iLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJv
cGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRpZXMi
LCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwgInRl
bXBsYXRlcyI6IFtdLCAidGV4dCI6ICJBV1MgR3VhcmREdXR5IFJlZ2lvbiIsICJ0b29sdGlwIjog
IiIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiYTU3ODljMzUtM2U2Zi00MjI5LWE2NzEtMmZlN2Jh
NmYzNDU3IiwgInZhbHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJi
bGFua19vcHRpb24iOiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0
cnVlLCAiY2hvc2VuIjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwg
ImRlcHJlY2F0ZWQiOiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiaW5jaWRlbnQvYXdzX2d1YXJkZHV0
eV9jb3VudCIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzNzgsICJpbnB1dF90
eXBlIjogInRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwgIm5h
bWUiOiAiYXdzX2d1YXJkZHV0eV9jb3VudCIsICJvcGVyYXRpb25fcGVybXMiOiB7fSwgIm9wZXJh
dGlvbnMiOiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJvcGVydGllcyIsICJy
ZWFkX29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6IFtdLCAidGVtcGxh
dGVzIjogW10sICJ0ZXh0IjogIkFXUyBHdWFyZER1dHkgQ291bnQiLCAidG9vbHRpcCI6ICIiLCAi
dHlwZV9pZCI6IDAsICJ1dWlkIjogImE2NGQ2OWNhLWZiMDEtNGJjMS1hMTAyLTJjZWVhMzBiNmI2
YiIsICJ2YWx1ZXMiOiBbXX0sIHsiYWxsb3dfZGVmYXVsdF92YWx1ZSI6IGZhbHNlLCAiYmxhbmtf
b3B0aW9uIjogZmFsc2UsICJjYWxjdWxhdGVkIjogZmFsc2UsICJjaGFuZ2VhYmxlIjogdHJ1ZSwg
ImNob3NlbiI6IGZhbHNlLCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2UsICJkZXBy
ZWNhdGVkIjogZmFsc2UsICJleHBvcnRfa2V5IjogImluY2lkZW50L2F3c19ndWFyZGR1dHlfZmlu
ZGluZ19pZCIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzNzksICJpbnB1dF90
eXBlIjogInRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwgIm5h
bWUiOiAiYXdzX2d1YXJkZHV0eV9maW5kaW5nX2lkIiwgIm9wZXJhdGlvbl9wZXJtcyI6IHt9LCAi
b3BlcmF0aW9ucyI6IFtdLCAicGxhY2Vob2xkZXIiOiAiIiwgInByZWZpeCI6ICJwcm9wZXJ0aWVz
IiwgInJlYWRfb25seSI6IGZhbHNlLCAicmljaF90ZXh0IjogZmFsc2UsICJ0YWdzIjogW10sICJ0
ZW1wbGF0ZXMiOiBbXSwgInRleHQiOiAiQVdTIEd1YXJkRHV0eSBGaW5kaW5nIElkIiwgInRvb2x0
aXAiOiAiIiwgInR5cGVfaWQiOiAwLCAidXVpZCI6ICJlMzgwYzMxNS02MDFkLTQwNTItOTBiNS03
OGVmZTc1ZDdlYWIiLCAidmFsdWVzIjogW119LCB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxz
ZSwgImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJs
ZSI6IHRydWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZh
bHNlLCAiZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9hd3NfZ3Vh
cmRkdXR5X2ZpbmRpbmdfYXJuIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDM4
MCwgImlucHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tlZCI6
IGZhbHNlLCAibmFtZSI6ICJhd3NfZ3VhcmRkdXR5X2ZpbmRpbmdfYXJuIiwgIm9wZXJhdGlvbl9w
ZXJtcyI6IHt9LCAib3BlcmF0aW9ucyI6IFtdLCAicGxhY2Vob2xkZXIiOiAiIiwgInByZWZpeCI6
ICJwcm9wZXJ0aWVzIiwgInJlYWRfb25seSI6IGZhbHNlLCAicmljaF90ZXh0IjogZmFsc2UsICJ0
YWdzIjogW10sICJ0ZW1wbGF0ZXMiOiBbXSwgInRleHQiOiAiQVdTIEd1YXJkRHV0eSBGaW5kaW5n
IEFybiIsICJ0b29sdGlwIjogIiIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiZjFjOGZhMjAtZmZj
My00OTQyLTk4YmItMWQ4NGZkYzkyZjMyIiwgInZhbHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0
X3ZhbHVlIjogZmFsc2UsICJibGFua19vcHRpb24iOiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxz
ZSwgImNoYW5nZWFibGUiOiB0cnVlLCAiY2hvc2VuIjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9i
eV9zZXJ2ZXIiOiBmYWxzZSwgImRlcHJlY2F0ZWQiOiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiaW5j
aWRlbnQvYXdzX2d1YXJkZHV0eV9yZXNvdXJjZV90eXBlIiwgImhpZGVfbm90aWZpY2F0aW9uIjog
ZmFsc2UsICJpZCI6IDM4MSwgImlucHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNl
LCAiaXNfdHJhY2tlZCI6IGZhbHNlLCAibmFtZSI6ICJhd3NfZ3VhcmRkdXR5X3Jlc291cmNlX3R5
cGUiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRl
ciI6ICIiLCAicHJlZml4IjogInByb3BlcnRpZXMiLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNo
X3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwgInRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJBV1Mg
R3VhcmREdXR5IFJlc291cmNlIFR5cGUiLCAidG9vbHRpcCI6ICIiLCAidHlwZV9pZCI6IDAsICJ1
dWlkIjogIjI1MWM4ZjJhLTlhOWQtNGIwZS1iOWEyLWVkMTVlMDIyNzU0YyIsICJ2YWx1ZXMiOiBb
XX0sIHsiYWxsb3dfZGVmYXVsdF92YWx1ZSI6IGZhbHNlLCAiYmxhbmtfb3B0aW9uIjogZmFsc2Us
ICJjYWxjdWxhdGVkIjogZmFsc2UsICJjaGFuZ2VhYmxlIjogdHJ1ZSwgImNob3NlbiI6IGZhbHNl
LCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2UsICJkZXByZWNhdGVkIjogZmFsc2Us
ICJleHBvcnRfa2V5IjogImluY2lkZW50L2F3c19ndWFyZGR1dHlfZGV0ZWN0b3JfaWQiLCAiaGlk
ZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlkIjogMzgyLCAiaW5wdXRfdHlwZSI6ICJ0ZXh0Iiwg
ImludGVybmFsIjogZmFsc2UsICJpc190cmFja2VkIjogZmFsc2UsICJuYW1lIjogImF3c19ndWFy
ZGR1dHlfZGV0ZWN0b3JfaWQiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25zIjog
W10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRpZXMiLCAicmVhZF9vbmx5
IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwgInRlbXBsYXRlcyI6IFtd
LCAidGV4dCI6ICJBV1MgR3VhcmREdXR5IERldGVjdG9yIElkIiwgInRvb2x0aXAiOiAiIiwgInR5
cGVfaWQiOiAwLCAidXVpZCI6ICI1ZTE5MTA0Ni1jOWNlLTRlNzQtYjViZS1mNzI3N2Y5Mzc5MmIi
LCAidmFsdWVzIjogW119LCB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5rX29w
dGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUsICJj
aG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVwcmVj
YXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9hd3NfZ3VhcmRkdXR5X2ZpbmRp
bmdfdHlwZSIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzODMsICJpbnB1dF90
eXBlIjogInRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwgIm5h
bWUiOiAiYXdzX2d1YXJkZHV0eV9maW5kaW5nX3R5cGUiLCAib3BlcmF0aW9uX3Blcm1zIjoge30s
ICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRp
ZXMiLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwg
InRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJBV1MgR3VhcmREdXR5IEZpbmRpbmcgVHlwZSIsICJ0
b29sdGlwIjogIiIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiNmZjNDIxYTMtYzQxNC00OGRlLTlk
MzktYmI4MzNiNzc3ZDAwIiwgInZhbHVlcyI6IFtdfSwgeyJleHBvcnRfa2V5IjogImluY2lkZW50
L2ludGVybmFsX2N1c3RvbWl6YXRpb25zX2ZpZWxkIiwgImlkIjogMCwgImlucHV0X3R5cGUiOiAi
dGV4dCIsICJpbnRlcm5hbCI6IHRydWUsICJuYW1lIjogImludGVybmFsX2N1c3RvbWl6YXRpb25z
X2ZpZWxkIiwgInJlYWRfb25seSI6IHRydWUsICJ0ZXh0IjogIkN1c3RvbWl6YXRpb25zIEZpZWxk
IChpbnRlcm5hbCkiLCAidHlwZV9pZCI6IDAsICJ1dWlkIjogImJmZWVjMmQ0LTM3NzAtMTFlOC1h
ZDM5LTRhMDAwNDA0NGFhMSJ9XSwgImZ1bmN0aW9ucyI6IFtdLCAiZ2VvcyI6IG51bGwsICJncm91
cHMiOiBudWxsLCAiaWQiOiA1LCAiaW5ib3VuZF9tYWlsYm94ZXMiOiBudWxsLCAiaW5jaWRlbnRf
YXJ0aWZhY3RfdHlwZXMiOiBbeyJkZXNjIjogIkFtYXpvbiBXZWIgU2VydmljZXMgKEFXUykgSUFN
IGFjY2VzcyBrZXkgaWQuIiwgImVuYWJsZWQiOiB0cnVlLCAiZXhwb3J0X2tleSI6ICJhd3NfaWFt
X2FjY2Vzc19rZXlfaWQiLCAiZmlsZSI6IGZhbHNlLCAiaWQiOiAwLCAibXVsdGlfYXdhcmUiOiBm
YWxzZSwgIm5hbWUiOiAiQVdTIElBTSBBY2Nlc3MgS2V5IElEIiwgInBhcnNlX2FzX2NzdiI6IGZh
bHNlLCAicHJvZ3JhbW1hdGljX25hbWUiOiAiYXdzX2lhbV9hY2Nlc3Nfa2V5X2lkIiwgInJlZ19l
eHAiOiBudWxsLCAic3lzdGVtIjogZmFsc2UsICJ0YWdzIjogW10sICJ1c2VfZm9yX3JlbGF0aW9u
c2hpcHMiOiB0cnVlLCAidXVpZCI6ICJhMzNhMTk3MS0xNjJjLTQ0MTctYjM0NC04NzA4ZjlkMjU2
NDQiLCAidmVyc2lvbiI6IDB9LCB7ImRlc2MiOiAiQW1hem9uIFdlYiBTZXJ2aWNlcyAoQVdTKSBJ
QU0gdXNlciBuYW1lLiIsICJlbmFibGVkIjogdHJ1ZSwgImV4cG9ydF9rZXkiOiAiYXdzX2lhbV91
c2VyX25hbWUiLCAiZmlsZSI6IGZhbHNlLCAiaWQiOiAwLCAibXVsdGlfYXdhcmUiOiBmYWxzZSwg
Im5hbWUiOiAiQVdTIElBTSBVc2VyIE5hbWUiLCAicGFyc2VfYXNfY3N2IjogZmFsc2UsICJwcm9n
cmFtbWF0aWNfbmFtZSI6ICJhd3NfaWFtX3VzZXJfbmFtZSIsICJyZWdfZXhwIjogbnVsbCwgInN5
c3RlbSI6IGZhbHNlLCAidGFncyI6IFtdLCAidXNlX2Zvcl9yZWxhdGlvbnNoaXBzIjogdHJ1ZSwg
InV1aWQiOiAiM2EwYTUzMDktYmEzMy00N2NiLTkyZGYtYzhhNTA2Zjg3MzE3IiwgInZlcnNpb24i
OiAwfV0sICJpbmNpZGVudF90eXBlcyI6IFt7InVwZGF0ZV9kYXRlIjogMTYwNzAwMDI0NTgwMywg
ImNyZWF0ZV9kYXRlIjogMTYwNzAwMDI0NTgwMywgInV1aWQiOiAiYmZlZWMyZDQtMzc3MC0xMWU4
LWFkMzktNGEwMDA0MDQ0YWEwIiwgImRlc2NyaXB0aW9uIjogIkN1c3RvbWl6YXRpb24gUGFja2Fn
ZXMgKGludGVybmFsKSIsICJleHBvcnRfa2V5IjogIkN1c3RvbWl6YXRpb24gUGFja2FnZXMgKGlu
dGVybmFsKSIsICJuYW1lIjogIkN1c3RvbWl6YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJl
bmFibGVkIjogZmFsc2UsICJzeXN0ZW0iOiBmYWxzZSwgInBhcmVudF9pZCI6IG51bGwsICJoaWRk
ZW4iOiBmYWxzZSwgImlkIjogMH1dLCAiaW5kdXN0cmllcyI6IG51bGwsICJsYXlvdXRzIjogW10s
ICJsb2NhbGUiOiBudWxsLCAibWVzc2FnZV9kZXN0aW5hdGlvbnMiOiBbXSwgIm5vdGlmaWNhdGlv
bnMiOiBudWxsLCAib3ZlcnJpZGVzIjogW10sICJwaGFzZXMiOiBbXSwgInJlZ3VsYXRvcnMiOiBu
dWxsLCAicm9sZXMiOiBbXSwgInNjcmlwdHMiOiBbXSwgInNlcnZlcl92ZXJzaW9uIjogeyJidWls
ZF9udW1iZXIiOiAzOCwgIm1ham9yIjogMzcsICJtaW5vciI6IDIsICJ2ZXJzaW9uIjogIjM3LjIu
MzgifSwgInRhZ3MiOiBbXSwgInRhc2tfb3JkZXIiOiBbXSwgInRpbWVmcmFtZXMiOiBudWxsLCAi
dHlwZXMiOiBbXSwgIndvcmtmbG93cyI6IFtdLCAid29ya3NwYWNlcyI6IFtdfQ==
""")
