# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_aws_guardduty"""

try:
    from resilient import ImportDefinition
except ImportError:
    # Support Apps running on resilient-circuits < v35.0.195
    from resilient_circuits.util import ImportDefinition


def codegen_reload_data():
    """
    Parameters required reload codegen for the fn_aws_guardduty package
    """
    return {
        "package": u"fn_aws_guardduty",
        "message_destinations": [],
        "functions": [],
        "workflows": [],
        "actions": [],
        "incident_fields": [u"aws_guardduty_finding_arn", u"aws_guardduty_finding_id", u"aws_guardduty_detector_id", u"aws_guardduty_region", u"aws_guardduty_finding_type", u"aws_guardduty_resource_type"],
        "incident_artifact_types": [],
        "datatables": [],
        "automatic_tasks": [],
        "scripts": []
    }


def customization_data(client=None):
    """
    Returns a Generator of ImportDefinitions (Customizations).
    Install them using `resilient-circuits customize`

    Contents:
    - Incident Fields:
        - aws_guardduty_finding_arn
        - aws_guardduty_finding_id
        - aws_guardduty_detector_id
        - aws_guardduty_region
        - aws_guardduty_finding_type
        - aws_guardduty_resource_type
    """

    yield ImportDefinition(u"""
eyJhY3Rpb25fb3JkZXIiOiBbXSwgImFjdGlvbnMiOiBbXSwgImFwcHMiOiBbXSwgImF1dG9tYXRp
Y190YXNrcyI6IFtdLCAiZXhwb3J0X2RhdGUiOiAxNjA2MjI3ODg0MTc0LCAiZXhwb3J0X2Zvcm1h
dF92ZXJzaW9uIjogMiwgImZpZWxkcyI6IFt7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwg
ImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6
IHRydWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNl
LCAiZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9hd3NfZ3VhcmRk
dXR5X3JlZ2lvbiIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzODAsICJpbnB1
dF90eXBlIjogInRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwg
Im5hbWUiOiAiYXdzX2d1YXJkZHV0eV9yZWdpb24iLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJv
cGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRpZXMi
LCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwgInRl
bXBsYXRlcyI6IFtdLCAidGV4dCI6ICJBV1MgR3VhcmREdXR5IFJlZ2lvbiIsICJ0b29sdGlwIjog
IiIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiYTU3ODljMzUtM2U2Zi00MjI5LWE2NzEtMmZlN2Jh
NmYzNDU3IiwgInZhbHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJi
bGFua19vcHRpb24iOiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0
cnVlLCAiY2hvc2VuIjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwg
ImRlcHJlY2F0ZWQiOiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiaW5jaWRlbnQvYXdzX2d1YXJkZHV0
eV9maW5kaW5nX2lkIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDM3NywgImlu
cHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tlZCI6IGZhbHNl
LCAibmFtZSI6ICJhd3NfZ3VhcmRkdXR5X2ZpbmRpbmdfaWQiLCAib3BlcmF0aW9uX3Blcm1zIjog
e30sICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3Bl
cnRpZXMiLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBb
XSwgInRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJBV1MgR3VhcmREdXR5IEZpbmRpbmcgSWQiLCAi
dG9vbHRpcCI6ICIiLCAidHlwZV9pZCI6IDAsICJ1dWlkIjogImUzODBjMzE1LTYwMWQtNDA1Mi05
MGI1LTc4ZWZlNzVkN2VhYiIsICJ2YWx1ZXMiOiBbXX0sIHsiYWxsb3dfZGVmYXVsdF92YWx1ZSI6
IGZhbHNlLCAiYmxhbmtfb3B0aW9uIjogZmFsc2UsICJjYWxjdWxhdGVkIjogZmFsc2UsICJjaGFu
Z2VhYmxlIjogdHJ1ZSwgImNob3NlbiI6IGZhbHNlLCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVy
IjogZmFsc2UsICJkZXByZWNhdGVkIjogZmFsc2UsICJleHBvcnRfa2V5IjogImluY2lkZW50L2F3
c19ndWFyZGR1dHlfZmluZGluZ19hcm4iLCAiaGlkZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlk
IjogMzc4LCAiaW5wdXRfdHlwZSI6ICJ0ZXh0IiwgImludGVybmFsIjogZmFsc2UsICJpc190cmFj
a2VkIjogZmFsc2UsICJuYW1lIjogImF3c19ndWFyZGR1dHlfZmluZGluZ19hcm4iLCAib3BlcmF0
aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJl
Zml4IjogInByb3BlcnRpZXMiLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxz
ZSwgInRhZ3MiOiBbXSwgInRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJBV1MgR3VhcmREdXR5IEZp
bmRpbmcgQXJuIiwgInRvb2x0aXAiOiAiIiwgInR5cGVfaWQiOiAwLCAidXVpZCI6ICJmMWM4ZmEy
MC1mZmMzLTQ5NDItOThiYi0xZDg0ZmRjOTJmMzIiLCAidmFsdWVzIjogW119LCB7ImFsbG93X2Rl
ZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6
IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hv
c2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6
ICJpbmNpZGVudC9hd3NfZ3VhcmRkdXR5X3Jlc291cmNlX3R5cGUiLCAiaGlkZV9ub3RpZmljYXRp
b24iOiBmYWxzZSwgImlkIjogMzgyLCAiaW5wdXRfdHlwZSI6ICJ0ZXh0IiwgImludGVybmFsIjog
ZmFsc2UsICJpc190cmFja2VkIjogZmFsc2UsICJuYW1lIjogImF3c19ndWFyZGR1dHlfcmVzb3Vy
Y2VfdHlwZSIsICJvcGVyYXRpb25fcGVybXMiOiB7fSwgIm9wZXJhdGlvbnMiOiBbXSwgInBsYWNl
aG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJvcGVydGllcyIsICJyZWFkX29ubHkiOiBmYWxzZSwg
InJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6IFtdLCAidGVtcGxhdGVzIjogW10sICJ0ZXh0Ijog
IkFXUyBHdWFyZER1dHkgUmVzb3VyY2UgVHlwZSIsICJ0b29sdGlwIjogIiIsICJ0eXBlX2lkIjog
MCwgInV1aWQiOiAiMjUxYzhmMmEtOWE5ZC00YjBlLWI5YTItZWQxNWUwMjI3NTRjIiwgInZhbHVl
cyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJibGFua19vcHRpb24iOiBm
YWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0cnVlLCAiY2hvc2VuIjog
ZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgImRlcHJlY2F0ZWQiOiBm
YWxzZSwgImV4cG9ydF9rZXkiOiAiaW5jaWRlbnQvYXdzX2d1YXJkZHV0eV9kZXRlY3Rvcl9pZCIs
ICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzODEsICJpbnB1dF90eXBlIjogInRl
eHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxzZSwgIm5hbWUiOiAiYXdz
X2d1YXJkZHV0eV9kZXRlY3Rvcl9pZCIsICJvcGVyYXRpb25fcGVybXMiOiB7fSwgIm9wZXJhdGlv
bnMiOiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJvcGVydGllcyIsICJyZWFk
X29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6IFtdLCAidGVtcGxhdGVz
IjogW10sICJ0ZXh0IjogIkFXUyBHdWFyZER1dHkgRGV0ZWN0b3IgSWQiLCAidG9vbHRpcCI6ICIi
LCAidHlwZV9pZCI6IDAsICJ1dWlkIjogIjVlMTkxMDQ2LWM5Y2UtNGU3NC1iNWJlLWY3Mjc3Zjkz
NzkyYiIsICJ2YWx1ZXMiOiBbXX0sIHsiYWxsb3dfZGVmYXVsdF92YWx1ZSI6IGZhbHNlLCAiYmxh
bmtfb3B0aW9uIjogZmFsc2UsICJjYWxjdWxhdGVkIjogZmFsc2UsICJjaGFuZ2VhYmxlIjogdHJ1
ZSwgImNob3NlbiI6IGZhbHNlLCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2UsICJk
ZXByZWNhdGVkIjogZmFsc2UsICJleHBvcnRfa2V5IjogImluY2lkZW50L2F3c19ndWFyZGR1dHlf
ZmluZGluZ190eXBlIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDM3OSwgImlu
cHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tlZCI6IGZhbHNl
LCAibmFtZSI6ICJhd3NfZ3VhcmRkdXR5X2ZpbmRpbmdfdHlwZSIsICJvcGVyYXRpb25fcGVybXMi
OiB7fSwgIm9wZXJhdGlvbnMiOiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJv
cGVydGllcyIsICJyZWFkX29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6
IFtdLCAidGVtcGxhdGVzIjogW10sICJ0ZXh0IjogIkFXUyBHdWFyZER1dHkgRmluZGluZyBUeXBl
IiwgInRvb2x0aXAiOiAiIiwgInR5cGVfaWQiOiAwLCAidXVpZCI6ICI2ZmM0MjFhMy1jNDE0LTQ4
ZGUtOWQzOS1iYjgzM2I3NzdkMDAiLCAidmFsdWVzIjogW119LCB7ImV4cG9ydF9rZXkiOiAiaW5j
aWRlbnQvaW50ZXJuYWxfY3VzdG9taXphdGlvbnNfZmllbGQiLCAiaWQiOiAwLCAiaW5wdXRfdHlw
ZSI6ICJ0ZXh0IiwgImludGVybmFsIjogdHJ1ZSwgIm5hbWUiOiAiaW50ZXJuYWxfY3VzdG9taXph
dGlvbnNfZmllbGQiLCAicmVhZF9vbmx5IjogdHJ1ZSwgInRleHQiOiAiQ3VzdG9taXphdGlvbnMg
RmllbGQgKGludGVybmFsKSIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiYmZlZWMyZDQtMzc3MC0x
MWU4LWFkMzktNGEwMDA0MDQ0YWExIn1dLCAiZnVuY3Rpb25zIjogW10sICJnZW9zIjogbnVsbCwg
Imdyb3VwcyI6IG51bGwsICJpZCI6IDEsICJpbmJvdW5kX21haWxib3hlcyI6IG51bGwsICJpbmNp
ZGVudF9hcnRpZmFjdF90eXBlcyI6IFtdLCAiaW5jaWRlbnRfdHlwZXMiOiBbeyJ1cGRhdGVfZGF0
ZSI6IDE2MDYyMjc4NTQ0MTksICJjcmVhdGVfZGF0ZSI6IDE2MDYyMjc4NTQ0MTksICJ1dWlkIjog
ImJmZWVjMmQ0LTM3NzAtMTFlOC1hZDM5LTRhMDAwNDA0NGFhMCIsICJkZXNjcmlwdGlvbiI6ICJD
dXN0b21pemF0aW9uIFBhY2thZ2VzIChpbnRlcm5hbCkiLCAiZXhwb3J0X2tleSI6ICJDdXN0b21p
emF0aW9uIFBhY2thZ2VzIChpbnRlcm5hbCkiLCAibmFtZSI6ICJDdXN0b21pemF0aW9uIFBhY2th
Z2VzIChpbnRlcm5hbCkiLCAiZW5hYmxlZCI6IGZhbHNlLCAic3lzdGVtIjogZmFsc2UsICJwYXJl
bnRfaWQiOiBudWxsLCAiaGlkZGVuIjogZmFsc2UsICJpZCI6IDB9XSwgImluZHVzdHJpZXMiOiBu
dWxsLCAibGF5b3V0cyI6IFtdLCAibG9jYWxlIjogbnVsbCwgIm1lc3NhZ2VfZGVzdGluYXRpb25z
IjogW10sICJub3RpZmljYXRpb25zIjogbnVsbCwgIm92ZXJyaWRlcyI6IFtdLCAicGhhc2VzIjog
W10sICJyZWd1bGF0b3JzIjogbnVsbCwgInJvbGVzIjogW10sICJzY3JpcHRzIjogW10sICJzZXJ2
ZXJfdmVyc2lvbiI6IHsiYnVpbGRfbnVtYmVyIjogMzgsICJtYWpvciI6IDM3LCAibWlub3IiOiAy
LCAidmVyc2lvbiI6ICIzNy4yLjM4In0sICJ0YWdzIjogW10sICJ0YXNrX29yZGVyIjogW10sICJ0
aW1lZnJhbWVzIjogbnVsbCwgInR5cGVzIjogW10sICJ3b3JrZmxvd3MiOiBbXSwgIndvcmtzcGFj
ZXMiOiBbXX0=
""")
