# -*- coding: utf-8 -*-
# Copyright IBM Corp. - Confidential Information
"""Generate the Resilient customizations required for fn_cisco_enforcement"""

from __future__ import print_function
from resilient_circuits.util import *


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # Function-field definitions
    yield TypeDefinition(
        {
            "type_name": "__function",
            "fields": { '022ccdd5-4303-4949-a2fb-472d7163c7ba': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_externalurl',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_externalurl',
                                            'tooltip': '',
                                            'uuid': '022ccdd5-4303-4949-a2fb-472d7163c7ba',
                                            'values': []},
  '152ee7fe-7dc9-4118-a02f-2c62d0be027a': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_src',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_src',
                                            'tooltip': '',
                                            'uuid': '152ee7fe-7dc9-4118-a02f-2c62d0be027a',
                                            'values': []},
  '27aecdca-a858-4ff5-bbf4-c18d20ee90a9': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_filename',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_filename',
                                            'tooltip': '',
                                            'uuid': '27aecdca-a858-4ff5-bbf4-c18d20ee90a9',
                                            'values': []},
  '3ed0b3ce-f6b0-4ddc-b724-5d6d5b96d7b0': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_eventdescription',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_eventdescription',
                                            'tooltip': '',
                                            'uuid': '3ed0b3ce-f6b0-4ddc-b724-5d6d5b96d7b0',
                                            'values': []},
  '4bde1794-0705-43f9-9d7b-860eb83c9958': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_eventtype',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_eventtype',
                                            'tooltip': '',
                                            'uuid': '4bde1794-0705-43f9-9d7b-860eb83c9958',
                                            'values': []},
  '545cc8ab-8bc7-487d-b395-213736518c07': { 'blank_option': False,
                                            'input_type': 'datetimepicker',
                                            'name': 'cisco_alerttime',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_alerttime',
                                            'tooltip': '',
                                            'uuid': '545cc8ab-8bc7-487d-b395-213736518c07',
                                            'values': []},
  '85487e13-cdab-45c6-b012-4ee01cfa19ee': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_dstip',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_dstip',
                                            'tooltip': '',
                                            'uuid': '85487e13-cdab-45c6-b012-4ee01cfa19ee',
                                            'values': []},
  '99ff12cf-f002-418a-ba75-2ff96137b522': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_deviceid',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_deviceid',
                                            'tooltip': '',
                                            'uuid': '99ff12cf-f002-418a-ba75-2ff96137b522',
                                            'values': []},
  'ae997d8b-f8e6-41a3-b1d6-1b96a12d9cbe': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_eventhash',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_eventhash',
                                            'tooltip': '',
                                            'uuid': 'ae997d8b-f8e6-41a3-b1d6-1b96a12d9cbe',
                                            'values': []},
  'be3abf5f-7b65-4c5f-8ac6-442535b39c03': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_dstdomain',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_dstdomain',
                                            'tooltip': '',
                                            'uuid': 'be3abf5f-7b65-4c5f-8ac6-442535b39c03',
                                            'values': []},
  'be5d67ad-96e3-47c2-975e-7a6080b829ca': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_protocolversion',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_protocolversion',
                                            'tooltip': '',
                                            'uuid': 'be5d67ad-96e3-47c2-975e-7a6080b829ca',
                                            'values': []},
  'c5239fd4-21af-469a-9ae6-c45aa9784c4b': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_dsturl',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_dsturl',
                                            'tooltip': '',
                                            'uuid': 'c5239fd4-21af-469a-9ae6-c45aa9784c4b',
                                            'values': []},
  'c8aef649-7963-4e67-a811-f6505ba2e206': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_deviceversion',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_deviceversion',
                                            'tooltip': '',
                                            'uuid': 'c8aef649-7963-4e67-a811-f6505ba2e206',
                                            'values': []},
  'd4e05190-1492-49e4-813d-f583726c50ae': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_providername',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_providername',
                                            'tooltip': '',
                                            'uuid': 'd4e05190-1492-49e4-813d-f583726c50ae',
                                            'values': []},
  'da7267dc-e822-45fa-8d18-297fbcbd2787': { 'blank_option': False,
                                            'input_type': 'datetimepicker',
                                            'name': 'cisco_eventtime',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_eventtime',
                                            'tooltip': '',
                                            'uuid': 'da7267dc-e822-45fa-8d18-297fbcbd2787',
                                            'values': []},
  'dc7a8e54-8a3b-406e-b34b-48f430c97544': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_eventseverity',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_eventseverity',
                                            'tooltip': '',
                                            'uuid': 'dc7a8e54-8a3b-406e-b34b-48f430c97544',
                                            'values': []},
  'e0bcee28-1db2-44c0-b20e-b1bf6f54feef': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_filehash',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_filehash',
                                            'tooltip': '',
                                            'uuid': 'e0bcee28-1db2-44c0-b20e-b1bf6f54feef',
                                            'values': []},
  'ed3dd357-0bd7-4698-970a-d31599159dbd': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_disabledstsafeguards',
                                            'placeholder': '',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_disabledstsafeguards',
                                            'tooltip': '',
                                            'uuid': 'ed3dd357-0bd7-4698-970a-d31599159dbd',
                                            'values': []},
  'fed7a3b2-0d32-4c12-acca-9db27090e0dc': { 'blank_option': False,
                                            'input_type': 'text',
                                            'name': 'cisco_domin',
                                            'placeholder': '',
                                            'required': 'always',
                                            'rich_text': False,
                                            'templates': [],
                                            'text': 'cisco_domin',
                                            'tooltip': '',
                                            'uuid': 'fed7a3b2-0d32-4c12-acca-9db27090e0dc',
                                            'values': []}}
        }
    )

    # Message destination: 'cisco_enforcement'
    yield MessageDestinationDefinition({ 'destination_type': 0,
  'expect_ack': True,
  'name': 'cisco_enforcement',
  'programmatic_name': 'cisco_enforcement'}
    )

    # Function: 'get_domains'
    yield FunctionDefinition({ 'description': { 'content': 'This is a function implementation that uses the Cisco API to gather the lists of domains already added to the shared customer\xe2\x80\x99s domain list',
                   'format': 'text'},
  'destination_handle': 'cisco_enforcement',
  'display_name': 'get_domains',
  'name': 'get_domains',
  'uuid': '7a478341-0da2-43db-9459-2fc87859c8e0',
  'view_items': []}
    )

    # Function: 'event'
    yield FunctionDefinition({ 'description': { 'content': 'This is a function implementation that uses the Cisco API to post a Malware event',
                   'format': 'text'},
  'destination_handle': 'cisco_enforcement',
  'display_name': 'event',
  'name': 'event',
  'uuid': 'ccbea7d3-ef1a-434d-8f30-330ef31ea1ab',
  'view_items': [ { 'content': '99ff12cf-f002-418a-ba75-2ff96137b522',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'c8aef649-7963-4e67-a811-f6505ba2e206',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'da7267dc-e822-45fa-8d18-297fbcbd2787',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '545cc8ab-8bc7-487d-b395-213736518c07',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'c5239fd4-21af-469a-9ae6-c45aa9784c4b',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'be3abf5f-7b65-4c5f-8ac6-442535b39c03',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'be5d67ad-96e3-47c2-975e-7a6080b829ca',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'd4e05190-1492-49e4-813d-f583726c50ae',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'ed3dd357-0bd7-4698-970a-d31599159dbd',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '85487e13-cdab-45c6-b012-4ee01cfa19ee',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'dc7a8e54-8a3b-406e-b34b-48f430c97544',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '4bde1794-0705-43f9-9d7b-860eb83c9958',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '3ed0b3ce-f6b0-4ddc-b724-5d6d5b96d7b0',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'ae997d8b-f8e6-41a3-b1d6-1b96a12d9cbe',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '27aecdca-a858-4ff5-bbf4-c18d20ee90a9',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': 'e0bcee28-1db2-44c0-b20e-b1bf6f54feef',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '022ccdd5-4303-4949-a2fb-472d7163c7ba',
                    'element': 'field_uuid',
                    'field_type': '__function'},
                  { 'content': '152ee7fe-7dc9-4118-a02f-2c62d0be027a',
                    'element': 'field_uuid',
                    'field_type': '__function'}]}
    )

    # Function: 'delete_domain'
    yield FunctionDefinition({ 'description': { 'content': 'This is a function implementation that uses the Cisco API to delete a domain from the shared customer\xe2\x80\x99s domain list.',
                   'format': 'text'},
  'destination_handle': 'cisco_enforcement',
  'display_name': 'delete_domain',
  'name': 'delete_domain',
  'uuid': '37d3c6c0-9b9b-4b96-bcd1-667c41a3b5de',
  'view_items': [ { 'content': 'fed7a3b2-0d32-4c12-acca-9db27090e0dc',
                    'element': 'field_uuid',
                    'field_type': '__function'}]}
    )

