#!/bin/bash -e

function getJsonVal() {
   releaseID=`python -c "import json,sys;print json.dumps(json.loads('''$1''')$2); sys.exit(0);"` ; 
   echo $releaseID
}

echo Getting Git Tag...
latestTag=$(git describe --tags)

echo Creating release...
echo '{"tag_name": "'$latestTag'","target_commitish": "master","name": "Internal Release '$latestTag'","body": "Generated by Jenkins","draft": false,"prerelease": true}' > json.json
output=$(curl -X POST -H 'Content-Type:application/json' -H 'Accept:application/json' --data-binary @json.json https://github.ibm.com/api/v3/repos/Resilient/resilient-community-apps/releases?access_token=$GIT_HUB_AUTH_TOKEN)
rm json.json

id=$(getJsonVal "$output" "['id']")
echo Release Id: $id
for file in ./rc[-_]*.zip; do
  echo Uploading file... ${file##*/}
  fileUpload=$(curl --data-binary @./${file##*/} -H "Authorization: token $GIT_HUB_AUTH_TOKEN" -H "Content-Type: application/octet-stream" https://github.ibm.com/api/uploads/repos/Resilient/resilient-community-apps/releases/"$id"/assets?name=${file##*/} )
  echo $fileUpload
done

for file in ./fn_*.zip; do
  echo Uploading file... ${file##*/}
  fileUpload=$(curl --data-binary @./${file##*/} -H "Authorization: token $GIT_HUB_AUTH_TOKEN" -H "Content-Type: application/octet-stream" https://github.ibm.com/api/uploads/repos/Resilient/resilient-community-apps/releases/"$id"/assets?name=${file##*/} )
  echo $fileUpload
done

for file in ./res_*.zip; do
  echo Uploading file... ${file##*/}
  fileUpload=$(curl --data-binary @./${file##*/} -H "Authorization: token $GIT_HUB_AUTH_TOKEN" -H "Content-Type: application/octet-stream" https://github.ibm.com/api/uploads/repos/Resilient/resilient-community-apps/releases/"$id"/assets?name=${file##*/} )
  echo $fileUpload
done




