# -*- coding: utf-8 -*-

"""Generate the Resilient customizations required for fn_secureworks_ctp"""

from __future__ import print_function
from resilient_circuits.util import *

def codegen_reload_data():
    """Parameters to codegen used to generate the fn_secureworks_ctp package"""
    reload_params = {"package": u"fn_secureworks_ctp",
                    "incident_fields": [u"scwx_ctp_date_created", u"scwx_ctp_grouping_type", u"scwx_ctp_priority", u"scwx_ctp_request_type", u"scwx_ctp_ticket_id", u"scwx_ctp_ticket_type"], 
                    "action_fields": [], 
                    "functions_params": [], 
                    "datatables": [], 
                    "message_destinations": [], 
                    "functions": [], 
                    "phases": [], 
                    "automatic_tasks": [], 
                    "scripts": [], 
                    "workflows": [],
                    "actions": [],
                    "incident_artifact_types": [] 
                    }
    return reload_params


def customization_data(client=None):
    """Produce any customization definitions (types, fields, message destinations, etc)
       that should be installed by `resilient-circuits customize`
    """

    # This import data contains:
    #   Incident fields:
    #     scwx_ctp_date_created
    #     scwx_ctp_grouping_type
    #     scwx_ctp_priority
    #     scwx_ctp_request_type
    #     scwx_ctp_ticket_id
    #     scwx_ctp_ticket_type


    yield ImportDefinition(u"""
eyJhY3Rpb25fb3JkZXIiOiBbXSwgImFjdGlvbnMiOiBbXSwgImF1dG9tYXRpY190YXNrcyI6IFtd
LCAiZXhwb3J0X2RhdGUiOiAxNTg0OTgzOTgxOTE4LCAiZXhwb3J0X2Zvcm1hdF92ZXJzaW9uIjog
MiwgImZpZWxkcyI6IFt7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxzZSwgImJsYW5rX29wdGlv
biI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJsZSI6IHRydWUsICJjaG9z
ZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZhbHNlLCAiZGVwcmVjYXRl
ZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9zY3d4X2N0cF9yZXF1ZXN0X3R5cGUi
LCAiaGlkZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlkIjogMzUyLCAiaW5wdXRfdHlwZSI6ICJ0
ZXh0IiwgImludGVybmFsIjogZmFsc2UsICJpc190cmFja2VkIjogZmFsc2UsICJuYW1lIjogInNj
d3hfY3RwX3JlcXVlc3RfdHlwZSIsICJvcGVyYXRpb25fcGVybXMiOiB7fSwgIm9wZXJhdGlvbnMi
OiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJvcGVydGllcyIsICJyZWFkX29u
bHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6IFtdLCAidGVtcGxhdGVzIjog
W10sICJ0ZXh0IjogIlNlY3VyZXdvcmtzIENUUCByZXF1ZXN0VHlwZSIsICJ0b29sdGlwIjogIiIs
ICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiNTViZTU4ODItZWVhYS00NGY1LThlNGUtNWU2ZmYxOTkw
MDhmIiwgInZhbHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjogZmFsc2UsICJibGFu
a19vcHRpb24iOiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5nZWFibGUiOiB0cnVl
LCAiY2hvc2VuIjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIiOiBmYWxzZSwgImRl
cHJlY2F0ZWQiOiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiaW5jaWRlbnQvc2N3eF9jdHBfdGlja2V0
X2lkIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDM0OCwgImlucHV0X3R5cGUi
OiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tlZCI6IGZhbHNlLCAibmFtZSI6
ICJzY3d4X2N0cF90aWNrZXRfaWQiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVyYXRpb25z
IjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRpZXMiLCAicmVhZF9v
bmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwgInRlbXBsYXRlcyI6
IFtdLCAidGV4dCI6ICJTZWN1cmV3b3JrcyBDVFAgdGlja2V0SWQiLCAidG9vbHRpcCI6ICIiLCAi
dHlwZV9pZCI6IDAsICJ1dWlkIjogIjVmZThiNjJkLTBhZTUtNDk5OS1iYmRjLTU0MWE3M2ZjOWVj
ZSIsICJ2YWx1ZXMiOiBbXX0sIHsiYWxsb3dfZGVmYXVsdF92YWx1ZSI6IGZhbHNlLCAiYmxhbmtf
b3B0aW9uIjogZmFsc2UsICJjYWxjdWxhdGVkIjogZmFsc2UsICJjaGFuZ2VhYmxlIjogdHJ1ZSwg
ImNob3NlbiI6IGZhbHNlLCAiZGVmYXVsdF9jaG9zZW5fYnlfc2VydmVyIjogZmFsc2UsICJkZXBy
ZWNhdGVkIjogZmFsc2UsICJleHBvcnRfa2V5IjogImluY2lkZW50L3Njd3hfY3RwX2dyb3VwaW5n
X3R5cGUiLCAiaGlkZV9ub3RpZmljYXRpb24iOiBmYWxzZSwgImlkIjogMzUxLCAiaW5wdXRfdHlw
ZSI6ICJ0ZXh0IiwgImludGVybmFsIjogZmFsc2UsICJpc190cmFja2VkIjogZmFsc2UsICJuYW1l
IjogInNjd3hfY3RwX2dyb3VwaW5nX3R5cGUiLCAib3BlcmF0aW9uX3Blcm1zIjoge30sICJvcGVy
YXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRpZXMiLCAi
cmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwgInRlbXBs
YXRlcyI6IFtdLCAidGV4dCI6ICJTZWN1cmV3b3JrcyBDVFAgZ3JvdXBpbmdUeXBlIiwgInRvb2x0
aXAiOiAiIiwgInR5cGVfaWQiOiAwLCAidXVpZCI6ICJiODdiNDBiZS03YWEwLTQ2NDItYmQ4MS0y
ZDBiNDc0ZjAxNDkiLCAidmFsdWVzIjogW119LCB7ImFsbG93X2RlZmF1bHRfdmFsdWUiOiBmYWxz
ZSwgImJsYW5rX29wdGlvbiI6IGZhbHNlLCAiY2FsY3VsYXRlZCI6IGZhbHNlLCAiY2hhbmdlYWJs
ZSI6IHRydWUsICJjaG9zZW4iOiBmYWxzZSwgImRlZmF1bHRfY2hvc2VuX2J5X3NlcnZlciI6IGZh
bHNlLCAiZGVwcmVjYXRlZCI6IGZhbHNlLCAiZXhwb3J0X2tleSI6ICJpbmNpZGVudC9zY3d4X2N0
cF90aWNrZXRfdHlwZSIsICJoaWRlX25vdGlmaWNhdGlvbiI6IGZhbHNlLCAiaWQiOiAzNTAsICJp
bnB1dF90eXBlIjogInRleHQiLCAiaW50ZXJuYWwiOiBmYWxzZSwgImlzX3RyYWNrZWQiOiBmYWxz
ZSwgIm5hbWUiOiAic2N3eF9jdHBfdGlja2V0X3R5cGUiLCAib3BlcmF0aW9uX3Blcm1zIjoge30s
ICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInByb3BlcnRp
ZXMiLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3MiOiBbXSwg
InRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJTZWN1cmV3b3JrcyBDVFAgdGlja2V0VHlwZSIsICJ0
b29sdGlwIjogIiIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiZTBlYzk3ZmUtNDZlOC00Yzk5LWIz
M2ItZGUyODA3Yjc1ZmYxIiwgInZhbHVlcyI6IFtdfSwgeyJhbGxvd19kZWZhdWx0X3ZhbHVlIjog
ZmFsc2UsICJibGFua19vcHRpb24iOiBmYWxzZSwgImNhbGN1bGF0ZWQiOiBmYWxzZSwgImNoYW5n
ZWFibGUiOiB0cnVlLCAiY2hvc2VuIjogZmFsc2UsICJkZWZhdWx0X2Nob3Nlbl9ieV9zZXJ2ZXIi
OiBmYWxzZSwgImRlcHJlY2F0ZWQiOiBmYWxzZSwgImV4cG9ydF9rZXkiOiAiaW5jaWRlbnQvc2N3
eF9jdHBfZGF0ZV9jcmVhdGVkIiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6IDM0
OSwgImlucHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tlZCI6
IGZhbHNlLCAibmFtZSI6ICJzY3d4X2N0cF9kYXRlX2NyZWF0ZWQiLCAib3BlcmF0aW9uX3Blcm1z
Ijoge30sICJvcGVyYXRpb25zIjogW10sICJwbGFjZWhvbGRlciI6ICIiLCAicHJlZml4IjogInBy
b3BlcnRpZXMiLCAicmVhZF9vbmx5IjogZmFsc2UsICJyaWNoX3RleHQiOiBmYWxzZSwgInRhZ3Mi
OiBbXSwgInRlbXBsYXRlcyI6IFtdLCAidGV4dCI6ICJTZWN1cmV3b3JrcyBDVFAgZGF0ZUNyZWF0
ZWQiLCAidG9vbHRpcCI6ICIiLCAidHlwZV9pZCI6IDAsICJ1dWlkIjogImY2ZTc4Njc3LWUxYzIt
NGU0ZC05NzA1LWZhMDIyYTBkMDNmZSIsICJ2YWx1ZXMiOiBbXX0sIHsiYWxsb3dfZGVmYXVsdF92
YWx1ZSI6IGZhbHNlLCAiYmxhbmtfb3B0aW9uIjogZmFsc2UsICJjYWxjdWxhdGVkIjogZmFsc2Us
ICJjaGFuZ2VhYmxlIjogdHJ1ZSwgImNob3NlbiI6IGZhbHNlLCAiZGVmYXVsdF9jaG9zZW5fYnlf
c2VydmVyIjogZmFsc2UsICJkZXByZWNhdGVkIjogZmFsc2UsICJleHBvcnRfa2V5IjogImluY2lk
ZW50L3Njd3hfY3RwX3ByaW9yaXR5IiwgImhpZGVfbm90aWZpY2F0aW9uIjogZmFsc2UsICJpZCI6
IDM1MywgImlucHV0X3R5cGUiOiAidGV4dCIsICJpbnRlcm5hbCI6IGZhbHNlLCAiaXNfdHJhY2tl
ZCI6IGZhbHNlLCAibmFtZSI6ICJzY3d4X2N0cF9wcmlvcml0eSIsICJvcGVyYXRpb25fcGVybXMi
OiB7fSwgIm9wZXJhdGlvbnMiOiBbXSwgInBsYWNlaG9sZGVyIjogIiIsICJwcmVmaXgiOiAicHJv
cGVydGllcyIsICJyZWFkX29ubHkiOiBmYWxzZSwgInJpY2hfdGV4dCI6IGZhbHNlLCAidGFncyI6
IFtdLCAidGVtcGxhdGVzIjogW10sICJ0ZXh0IjogIlNlY3VyZXdvcmtzIENUUCBwcmlvcml0eSIs
ICJ0b29sdGlwIjogIiIsICJ0eXBlX2lkIjogMCwgInV1aWQiOiAiZGFjMWUwMTYtNGUzMS00OWI1
LWE0MTYtN2EyZmI0YzE0MDRmIiwgInZhbHVlcyI6IFtdfV0sICJmdW5jdGlvbnMiOiBbXSwgImdl
b3MiOiBudWxsLCAiZ3JvdXBzIjogbnVsbCwgImlkIjogOCwgImluYm91bmRfbWFpbGJveGVzIjog
bnVsbCwgImluY2lkZW50X2FydGlmYWN0X3R5cGVzIjogW10sICJpbmNpZGVudF90eXBlcyI6IFt7
InVwZGF0ZV9kYXRlIjogMTU4NTA3NzkwMDg4MCwgImNyZWF0ZV9kYXRlIjogMTU4NTA3NzkwMDg4
MCwgInV1aWQiOiAiYmZlZWMyZDQtMzc3MC0xMWU4LWFkMzktNGEwMDA0MDQ0YWEwIiwgImRlc2Ny
aXB0aW9uIjogIkN1c3RvbWl6YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJleHBvcnRfa2V5
IjogIkN1c3RvbWl6YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJuYW1lIjogIkN1c3RvbWl6
YXRpb24gUGFja2FnZXMgKGludGVybmFsKSIsICJlbmFibGVkIjogZmFsc2UsICJzeXN0ZW0iOiBm
YWxzZSwgInBhcmVudF9pZCI6IG51bGwsICJoaWRkZW4iOiBmYWxzZSwgImlkIjogMH1dLCAiaW5k
dXN0cmllcyI6IG51bGwsICJsYXlvdXRzIjogW10sICJsb2NhbGUiOiBudWxsLCAibWVzc2FnZV9k
ZXN0aW5hdGlvbnMiOiBbXSwgIm5vdGlmaWNhdGlvbnMiOiBudWxsLCAib3ZlcnJpZGVzIjogW10s
ICJwaGFzZXMiOiBbXSwgInJlZ3VsYXRvcnMiOiBudWxsLCAicm9sZXMiOiBbXSwgInNjcmlwdHMi
OiBbXSwgInNlcnZlcl92ZXJzaW9uIjogeyJidWlsZF9udW1iZXIiOiAzMiwgIm1ham9yIjogMzUs
ICJtaW5vciI6IDIsICJ2ZXJzaW9uIjogIjM1LjIuMzIifSwgInRhZ3MiOiBbXSwgInRhc2tfb3Jk
ZXIiOiBbXSwgInRpbWVmcmFtZXMiOiBudWxsLCAidHlwZXMiOiBbXSwgIndvcmtmbG93cyI6IFtd
LCAid29ya3NwYWNlcyI6IFtdfQ==
"""
    )